/* ===================== village life: talk, drinking, villagers, fires & water cannon ===================== */
const LIFE={t:0,spray:false,fire:null,nextFire:75,parts:null,pi:0,pv:[],said:0,villagers:[]};
function bubble(A,text,dur){ if(!A.bub){ const sp=new THREE.Sprite(new THREE.SpriteMaterial({transparent:true,depthTest:false,depthWrite:false})); sp.renderOrder=25; A.group.add(sp); A.bub=sp; } A.bub.position.y=A.bubY||2.62;
  const c=cvs(640,150), g=c.getContext('2d'); g.clearRect(0,0,640,150); g.font='800 44px Manrope, Arial'; const w=Math.min(620,g.measureText(text).width+60); const x0=(640-w)/2; g.fillStyle='rgba(255,255,255,0.95)'; g.beginPath(); g.roundRect?g.roundRect(x0,8,w,96,40):g.rect(x0,8,w,96); g.fill(); g.beginPath(); g.moveTo(300,100); g.lineTo(340,100); g.lineTo(316,140); g.fill();
  g.fillStyle='#161616'; g.textAlign='center'; g.textBaseline='middle'; g.fillText(text,320,58); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; if(A.bub.material.map) A.bub.material.map.dispose(); A.bub.material.map=t; A.bub.material.needsUpdate=true; A.bub.scale.set(2.3,0.54,1); A.bub.visible=true; A.bubT=dur||4; }
function holdGlass(A,col){ if(A.glass) return; const g=new THREE.Mesh(new THREE.CylinderGeometry(0.04,0.035,0.14,10),new THREE.MeshStandardMaterial({color:col||0xd99a22,transparent:true,opacity:0.85,roughness:0.2})); g.position.set(0,-0.62,-0.06); A.armR.add(g); A.glass=g; }
function npcByName(n){ const N=NPCS.find(q=>q.d.n===n); return N||null; }
function roadPath(x0,z0,len,off){ const pts=[]; let n=nearestRoad(x0,z0,60); if(!n) return pts; let x=n.s.x, z=n.s.z, tx=n.s.tx, tz=n.s.tz;
  for(let d=0;d<len;d+=4){ const w=n.s.w||6; pts.push([x-tz*w*off,z+tx*w*off]); const nx=x+tx*4, nz=z+tz*4; const m=nearestRoad(nx,nz,12); if(!m) break; let mtx=m.s.tx, mtz=m.s.tz; if(mtx*tx+mtz*tz<0){ mtx=-mtx; mtz=-mtz; } x=m.s.x; z=m.s.z; tx=mtx; tz=mtz; n=m; } return pts; }
function villagers(){ if(LIFE.villagers.length) return; const add=(n,c,opt,f)=>{ const A=makePerson(n,c,opt); GAME.scene.add(A.group); const V={A,n,t:Math.random()*10,f}; LIFE.villagers.push(V); return V; };
  if(LANDMARKS.fire){ const L=LANDMARKS.fire; const V=add('Vatrogasac Krtek','#1f2f4f'); const A=V.A; const hm=new THREE.Mesh(new THREE.SphereGeometry(0.17,14,10,0,TAU,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0xc8161d,roughness:0.4})); hm.position.y=1.72; A.group.add(hm); for(const y of [0.95,1.25]){ const st=new THREE.Mesh(new THREE.BoxGeometry(0.46,0.05,0.34),new THREE.MeshStandardMaterial({color:0xf2e03a,emissive:0x4a4200})); st.position.y=y; A.group.add(st); }
    const dx=L.look[0]-L.x, dz=L.look[1]-L.z, dl=Math.hypot(dx,dz)||1; A.group.position.set(L.x+dx/dl*6,groundAt(L.x+dx/dl*6,L.z+dz/dl*6),L.z+dz/dl*6); A.group.rotation.y=faceYaw(-dx,-dz); V.f=(V,dt)=>{ V.A.armR.rotation.x=-0.4+Math.sin(V.t*1.2)*0.3; if(Math.random()<dt*0.02) bubble(V.A,LIFE.fire?'Gori! Brzo u kamion!':'Sve mirno u Tuhelju',4); }; }
  const tp=[-262,-38], tq=[-259.5,-38.6];
  { const V=add('Tuljulju','#8a4b2a'); V.A.group.position.set(tp[0],groundAt(tp[0],tp[1]),tp[1]); V.A.group.rotation.y=faceYaw(tq[0]-tp[0],tq[1]-tp[1]); V.f=(V,dt)=>{ V.A.armR.rotation.x=-0.3+Math.sin(V.t*2.1)*0.5; V.A.armL.rotation.x=-0.2+Math.sin(V.t*1.3)*0.2; if(Math.random()<dt*0.025) bubble(V.A,['Kaj ima novoga?','Ajmo na gemišt!','Vidiš ti to…'][Math.floor(Math.random()*3)],3.5); }; }
  { const V=add('Prgac','#3a6b8a'); V.A.group.position.set(tq[0],groundAt(tq[0],tq[1]),tq[1]); V.A.group.rotation.y=faceYaw(tp[0]-tq[0],tp[1]-tq[1]); V.f=(V,dt)=>{ V.A.armL.rotation.x=-0.3+Math.sin(V.t*1.7+1)*0.4; if(Math.random()<dt*0.025) bubble(V.A,['Ma daj!','Je, je…','Idemo kod Putnika!'][Math.floor(Math.random()*3)],3.5); }; }
  { const path=roadPath(-392,6,420,0.32); if(path.length>10){ const V=add('Šemso','#2e7d4f'); const bk=makeBike(0x1f5fb0); V.A.group.add(bk.g); V.bike=bk; V.path=path; V.u=0; V.dir=1; V.A.armL.rotation.x=V.A.armR.rotation.x=-1.05;
      V.f=(V,dt)=>{ const P=V.path; V.u+=dt*5.2*V.dir/4; if(V.u>=P.length-1){ V.u=P.length-1.001; V.dir=-1; } if(V.u<=0){ V.u=0.001; V.dir=1; } const i=Math.floor(V.u), k=V.u-i; const a=P[i], b=P[Math.min(P.length-1,i+1)]; const x=a[0]+(b[0]-a[0])*k, z=a[1]+(b[1]-a[1])*k; V.A.group.position.set(x,groundAt(x,z)+0.06,z); V.A.group.rotation.y=faceYaw((b[0]-a[0])*V.dir,(b[1]-a[1])*V.dir); const ph=V.t*5.2/0.34; V.bike.spin(ph); V.A.bikeT=GAME.time; V.A.bikePh=ph*0.5; V.A.legL.rotation.x=-0.75+Math.sin(ph*0.5)*0.42; V.A.legR.rotation.x=-0.75-Math.sin(ph*0.5)*0.42; if(Math.random()<dt*0.012) bubble(V.A,'Pazi, bicikl! 🚲',3); }; } }
  { const path=roadPath(-300,-20,120,0.62); if(path.length>6){ const V=add('Poljanec Martin','#6b5a3a'); const st=new THREE.Mesh(new THREE.CylinderGeometry(0.02,0.02,1.05,6),new THREE.MeshStandardMaterial({color:0x9aa0a6,metalness:0.7,roughness:0.3})); st.position.set(0,-0.55,-0.05); V.A.armR.add(st); V.path=path; V.u=0; V.dir=1;
      V.f=(V,dt)=>{ const P=V.path; V.u+=dt*0.55*V.dir/4; if(V.u>=P.length-1){ V.u=P.length-1.001; V.dir=-1; } if(V.u<=0){ V.u=0.001; V.dir=1; } const i=Math.floor(V.u), k=V.u-i; const a=P[i], b=P[Math.min(P.length-1,i+1)]; const x=a[0]+(b[0]-a[0])*k, z=a[1]+(b[1]-a[1])*k; V.A.group.position.set(x,groundAt(x,z),z); V.A.group.rotation.y=faceYaw((b[0]-a[0])*V.dir,(b[1]-a[1])*V.dir); const ph=V.t*3.2; V.A.legL.rotation.x=Math.sin(ph)*0.35; V.A.legR.rotation.x=-Math.sin(ph)*0.2; V.A.armR.rotation.x=-0.15+Math.sin(ph)*0.25; V.A.group.rotation.z=Math.sin(ph)*0.05; if(Math.random()<dt*0.01) bubble(V.A,'Polako, polako…',3); }; } } }
/* Kenka & Jovo: drink, ask for another round, now and then a wobbly walk */
function barRegulars(dt){ for(const nm of ['Kenka','Jovo']){ const N=npcByName(nm); if(!N) continue; const A=N.A, d=N.d; holdGlass(A); if(N.walk===undefined){ N.walk=null; N.nextWalk=40+Math.random()*60; N.nextSay=8+Math.random()*20; }
    N.nextSay-=dt; if(N.nextSay<=0&&!N.walk){ N.nextSay=22+Math.random()*25; bubble(A,'Lidija, daj još rundu!',4); const L=npcByName('Lidija'); if(L) setTimeout(()=>bubble(L.A,['Evo, dečki!','Stiže runda!','Opet vi dva…'][Math.floor(Math.random()*3)],3.5),1600); }
    if(!N.walk){ N.nextWalk-=dt; const u=(N.t*0.35)%1; A.armR.rotation.x=u<0.15?-2.2:-0.75; if(N.nextWalk<=0){ const ox=d.x, oz=d.z; const ang=Math.random()*TAU; N.walk={t:0,dur:14,ox,oz,tx:ox+Math.cos(ang)*3.5,tz:oz+Math.sin(ang)*3.5}; bubble(A,['Idem malo prošetat…','Hik!','Gdje su mi cigarete?'][Math.floor(Math.random()*3)],3); } }
    else { A.seatT=-1; const W=N.walk; W.t+=dt; const h=W.t/W.dur; const k=h<0.5?h*2:2-h*2; const wob=Math.sin(W.t*2.3)*0.5; const x=W.ox+(W.tx-W.ox)*k+Math.cos(W.t*1.7)*0.25, z=W.oz+(W.tz-W.oz)*k+Math.sin(W.t*1.3)*0.25; A.group.position.set(x,d.y+0.08,z); A.group.rotation.y=faceYaw((W.tx-W.ox)*(h<0.5?1:-1),(W.tz-W.oz)*(h<0.5?1:-1))+wob*0.4; A.group.rotation.z=Math.sin(W.t*3.1)*0.12;
      const ph=W.t*4.5; A.legL.rotation.x=Math.sin(ph)*0.45; A.legR.rotation.x=-Math.sin(ph)*0.45; A.armL.rotation.x=-0.3+Math.sin(ph*0.7)*0.5; A.armR.rotation.x=-0.9;
      if(W.t>=W.dur){ N.walk=null; N.nextWalk=60+Math.random()*80; A.group.position.set(d.x,d.y,d.z); A.group.rotation.set(0,d.face,0); A.legL.rotation.x=A.legR.rotation.x=-1.2; } } } }
/* ---- fires ---- */
let FIRE_TEX=null; function fireTex(){ if(FIRE_TEX) return FIRE_TEX; const c=cvs(128,256), g=c.getContext('2d'); const gr=g.createRadialGradient(64,190,4,64,170,110); gr.addColorStop(0,'rgba(255,250,210,1)'); gr.addColorStop(0.25,'rgba(255,196,60,0.95)'); gr.addColorStop(0.6,'rgba(236,84,20,0.7)'); gr.addColorStop(1,'rgba(120,20,0,0)'); g.fillStyle=gr; g.beginPath(); g.moveTo(64,6); g.bezierCurveTo(128,120,120,250,64,250); g.bezierCurveTo(8,250,0,120,64,6); g.fill(); FIRE_TEX=new THREE.CanvasTexture(c); FIRE_TEX.colorSpace=THREE.SRGBColorSpace; return FIRE_TEX; }
function startFire(){ const c=CENTER; const cand=BLD.filter(b=>!b.custom&&b.rect&&Math.hypot(b.rect[0]-c[0],b.rect[1]-c[1])<260&&b.rect[3]*b.rect[4]>40); if(!cand.length) return; const b=cand[Math.floor(Math.random()*cand.length)]; const x=b.rect[0], z=b.rect[1]; const y=(b.hmax||getHeight(x,z))+(b.lev||2)*2.9+1.2;
  const g=new THREE.Group(); const fl=[]; for(let i=0;i<14;i++){ const add=i%2===0; const s=new THREE.Sprite(new THREE.SpriteMaterial({map:fireTex(),transparent:true,depthWrite:false,blending:add?THREE.AdditiveBlending:THREE.NormalBlending,color:add?0xffffff:0xff7a2a})); s.position.set((Math.random()-0.5)*b.rect[3]*0.7,Math.random()*1.8,(Math.random()-0.5)*b.rect[4]*0.7); s.userData.ph=Math.random()*10; s.userData.base=3.6+Math.random()*3.2; g.add(s); fl.push(s); }
  g.position.set(x,y,z); GAME.scene.add(g); LIFE.fire={g,fl,hp:100,x,y,z,b,t:0}; UI.toast('🔥 Požar! Gori kuća u selu — vatrogasci, u kamion!'); }
function fireTick(dt){ const F=LIFE.fire; const ind=document.getElementById('fireind');
  if(!F){ LIFE.nextFire-=dt; if(LIFE.nextFire<=0) startFire(); if(ind) ind.style.display='none'; return; }
  F.t+=dt; const k=F.hp/100; for(const s of F.fl){ const ph=F.t*6+s.userData.ph; const sc=s.userData.base*(0.75+0.25*Math.sin(ph))*(0.25+0.75*k); s.scale.set(sc*0.6,sc,1); s.material.opacity=0.5+0.5*k; }
  if(Math.random()<dt*14*k) puff(new THREE.Vector3(F.x+(Math.random()-0.5)*4,F.y+3.5,F.z+(Math.random()-0.5)*4),3.4,0x2e2d2b);
  if(ind){ const d=Math.hypot(F.x-PLAYER.pos.x,F.z-PLAYER.pos.z); const bear=Math.atan2(F.x-PLAYER.pos.x,-(F.z-PLAYER.pos.z)); const rel=bear-(-PLAYER.yaw); ind.style.display='block'; ind.textContent='🔥 Požar '+Math.round(d)+' m  '+['⬆️','↗️','➡️','↘️','⬇️','↙️','⬅️','↖️'][((Math.round(rel/(Math.PI/4))%8)+8)%8]; }
  if(F.hp<=0){ GAME.scene.remove(F.g); for(const s of F.fl) s.material.dispose(); for(let i=0;i<10;i++) puff(new THREE.Vector3(F.x+(Math.random()-0.5)*4,F.y+1+Math.random()*2,F.z+(Math.random()-0.5)*4),2.5,0xdedbd4); LIFE.fire=null; LIFE.nextFire=90+Math.random()*90; UI.toast('💧 Požar ugašen! Bravo vatrogasci 🚒'); if(PLAYER.driving&&PLAYER.driving.truck&&!GTA.mission) money(150,'ugašen požar'); } }
/* ---- water cannon on the fire truck ---- */
function waterInit(){ if(LIFE.parts) return; const m=new THREE.InstancedMesh(new THREE.SphereGeometry(0.16,8,6),new THREE.MeshStandardMaterial({color:0xe6f4ff,emissive:0x1a3a5a,transparent:true,opacity:0.8,roughness:0.1,metalness:0,depthWrite:false}),420); m.count=0; m.frustumCulled=false; GAME.scene.add(m); LIFE.parts=m; }
function emitWater(v,dir,n){ const s=v.st; const p=new THREE.Vector3(1.4,3.2,0); v.group.updateMatrixWorld(); v.group.localToWorld(p); for(let i=0;i<n;i++){ if(LIFE.pv.length>=420) LIFE.pv.shift(); const d=dir.clone(); d.x+=(Math.random()-0.5)*0.06; d.y+=(Math.random()-0.5)*0.06; d.z+=(Math.random()-0.5)*0.06; d.normalize(); LIFE.pv.push({p:p.clone(),v:d.multiplyScalar(26+Math.random()*3),t:0}); } }
function waterTick(dt){ waterInit(); const v=PLAYER.driving; let dir=null; if(v&&v.truck&&(LIFE.spray||KEYS.KeyG)){ dir=new THREE.Vector3(0,0,-1).applyQuaternion(GAME.camera.quaternion); dir.y=Math.max(dir.y,0)+0.14; dir.normalize(); LIFE.acc=(LIFE.acc||0)+dt*110; const nE=Math.floor(LIFE.acc); LIFE.acc-=nE; emitWater(v,dir,nE); LIFE.sprayOn=true; } else LIFE.sprayOn=false;
  for(const o of DRIVE){ if(!o.truck||!o.remote) continue; const R=NET.remotes.get(o.remote); if(R&&R.wa){ const d=new THREE.Vector3(-Math.sin(o.st.yaw+(R.wy||0)),0.28,-Math.cos(o.st.yaw+(R.wy||0))).normalize(); o.wacc=(o.wacc||0)+dt*90; const nE=Math.floor(o.wacc); o.wacc-=nE; emitWater(o,d,nE); } }
  const F=LIFE.fire; const M=new THREE.Matrix4(); let n=0; for(let i=LIFE.pv.length-1;i>=0;i--){ const P=LIFE.pv[i]; P.t+=dt; P.v.y-=9.8*dt; P.p.addScaledVector(P.v,dt); let dead=P.t>2.2||P.p.y<getHeight(P.p.x,P.p.z);
      if(F&&!dead&&Math.hypot(P.p.x-F.x,P.p.z-F.z)<Math.max(3.5,Math.max(F.b.rect[3],F.b.rect[4])*0.55)&&Math.abs(P.p.y-F.y)<4.5){ F.hp-=0.16; dead=true; }
      if(dead){ if(Math.random()<0.05) puff(P.p.clone(),0.5,0xe8f2ff); LIFE.pv.splice(i,1); continue; } }
  for(const P of LIFE.pv){ if(n>=420) break; M.makeTranslation(P.p.x,P.p.y,P.p.z); LIFE.parts.setMatrixAt(n++,M); } LIFE.parts.count=n; LIFE.parts.instanceMatrix.needsUpdate=true;
  const wb=document.getElementById('waterbtn'); if(wb) wb.classList.toggle('on',!!(PLAYER.driving&&PLAYER.driving.truck)); }
function lifeTick(dt){ LIFE.t+=dt; villagers(); for(const V of LIFE.villagers){ V.t+=dt; if(V.f) V.f(V,dt); } barRegulars(dt); valentinaTick(dt); for(const n of ['Kenka','Jovo','Kiki Poljanec']){ const N=npcByName(n); if(N) N.A.bubY=1.95; } { const L=npcByName('Lidija'); if(L) L.A.bubY=2.35; }
  for(const A of [...NPCS.map(n=>n.A),...LIFE.villagers.map(v=>v.A)]){ if(A.bub&&A.bubT>0){ A.bubT-=dt; if(A.bubT<=0) A.bub.visible=false; } }
  fireTick(dt); waterTick(dt); }

function makeBike(frameCol){ const g=new THREE.Group(); const fm=new THREE.MeshStandardMaterial({color:frameCol,metalness:0.6,roughness:0.3}), tm=new THREE.MeshStandardMaterial({color:0x121212,roughness:0.85}), cm=new THREE.MeshStandardMaterial({color:0xd6dade,metalness:0.95,roughness:0.2}), sm=new THREE.MeshStandardMaterial({color:0x1a1a1a,roughness:0.6});
  const tube=(a,b,r,m,parent)=>{ const d=new THREE.Vector3(b[0]-a[0],b[1]-a[1],b[2]-a[2]); const L=d.length(); const t=new THREE.Mesh(new THREE.CylinderGeometry(r,r,L,8),m); t.position.set((a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2); t.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize()); t.castShadow=true; (parent||g).add(t); return t; };
  const R=[0,0.34,0.53], F=[0,0.34,-0.53], BB=[0,0.3,0.08], S=[0,0.8,0.2], H1=[0,0.86,-0.34], H2=[0,0.72,-0.38];
  tube(S,H1,0.018,fm); tube(BB,H2,0.022,fm); tube(BB,S,0.019,fm); for(const sx of [-0.05,0.05]){ tube([sx,BB[1],BB[2]],[sx,R[1],R[2]],0.011,fm); tube([sx,0.78,0.21],[sx,R[1],R[2]],0.01,fm); tube([sx*0.9,H2[1],H2[2]],[sx,F[1],F[2]],0.012,fm); }
  tube(H2,H1,0.024,fm); tube(H1,[0,0.97,-0.36],0.016,cm); tube([-0.27,0.98,-0.33],[0.27,0.98,-0.33],0.013,cm); for(const sx of [-0.3,0.3]) tube([sx*0.85,0.98,-0.33],[sx,0.98,-0.33],0.018,sm);
  tube(S,[0,0.9,0.22],0.014,cm); { const sd=new THREE.Mesh(new THREE.SphereGeometry(0.1,12,8),sm); sd.scale.set(0.75,0.28,1.25); sd.position.set(0,0.92,0.2); g.add(sd); }
  { const fe=new THREE.Mesh(new THREE.TorusGeometry(0.37,0.02,6,16,Math.PI*0.7),fm); fe.rotation.set(0,Math.PI/2,Math.PI*0.25); fe.position.set(0,0.34,0.53); g.add(fe); }
  const wheels=[]; for(const c of [R,F]){ const w=new THREE.Group(); w.position.set(c[0],c[1],c[2]); const tire=new THREE.Mesh(new THREE.TorusGeometry(0.33,0.022,10,32),tm); tire.rotation.y=Math.PI/2; w.add(tire); const rim=new THREE.Mesh(new THREE.TorusGeometry(0.305,0.01,6,32),cm); rim.rotation.y=Math.PI/2; w.add(rim);
    for(let k=0;k<18;k++){ const a=k/18*TAU; tube([0,0,0],[k%2?0.012:-0.012,Math.cos(a)*0.3,Math.sin(a)*0.3],0.0025,cm,w); } const hub=new THREE.Mesh(new THREE.CylinderGeometry(0.025,0.025,0.1,10),cm); hub.rotation.z=Math.PI/2; w.add(hub); g.add(w); wheels.push(w); }
  const crank=new THREE.Group(); crank.position.set(0,BB[1],BB[2]); const ring=new THREE.Mesh(new THREE.TorusGeometry(0.095,0.008,6,24),cm); ring.rotation.y=Math.PI/2; ring.position.x=0.06; crank.add(ring);
  for(const sd of [-1,1]){ const arm=tube([sd*0.07,0,0],[sd*0.07,-sd*0.17,0],0.012,cm,crank); const pd=new THREE.Mesh(new THREE.BoxGeometry(0.1,0.02,0.07),sm); pd.position.set(sd*0.12,-sd*0.17,0); crank.add(pd); } g.add(crank);
  tube([0.06,BB[1]+0.09,BB[2]],[0.06,R[1]+0.03,R[2]],0.004,sm); tube([0.06,BB[1]-0.09,BB[2]],[0.06,R[1]-0.03,R[2]],0.004,sm);
  return {g,spin:(ph)=>{ for(const w of wheels) w.rotation.x=-ph; crank.rotation.x=-ph*0.5; }}; }

function cafeRoute(k){ const C=LANDMARKS.cafeF; if(!C) return []; const q=(x,z)=>{ const p=C.f(x,0,z); return [p[0],p[2]]; }; return k==='toBar'?[q(4.4,2.8),q(2.7,2.8),q(0.6,-1.9)]:[q(2.7,2.8),q(4.4,2.8)]; }
function nearValentina(){ const V=npcByName('Valentina'); if(!V||!V.srv||V.srv.st!=='ask') return false; const p=V.A.group.position; return Math.hypot(PLAYER.pos.x-p.x,PLAYER.pos.z-p.z)<3.2; }
function valentinaTick(dt){ const N=npcByName('Valentina'); if(!N) return; const A=N.A, d=N.d; if(!N.srv){ N.srv={st:'patrol',cd:8,route:[]}; const tray=new THREE.Group(); const tr=new THREE.Mesh(new THREE.CylinderGeometry(0.19,0.19,0.015,20),new THREE.MeshStandardMaterial({color:0xcfd3d6,metalness:0.9,roughness:0.25})); tray.add(tr); const gl=new THREE.Mesh(new THREE.CylinderGeometry(0.04,0.035,0.14,10),new THREE.MeshStandardMaterial({color:0xd99a22,transparent:true,opacity:0.85})); gl.position.y=0.08; tray.add(gl); tray.position.set(0,-0.6,-0.12); tray.rotation.x=1.35; tray.visible=false; A.armR.add(tray); N.tray=tray; }
  const S=N.srv; const P=A.group.position; const me=PLAYER.pos; const dm=Math.hypot(me.x-P.x,me.z-P.z); S.cd-=dt;
  const T=LANDMARKS.terrace; const onTerrace=T&&Math.hypot(me.x-T.x,me.z-T.z)<7.5&&Math.abs(me.y-d.y)<1.5&&!PLAYER.driving&&!PKC.sit;
  const walkTo=(tx,tz,sp)=>{ const dx=tx-P.x, dz=tz-P.z, L=Math.hypot(dx,dz); if(L<0.05) return true; const st=Math.min(L,sp*dt); P.x+=dx/L*st; P.z+=dz/L*st; P.y=d.y; A.group.rotation.y=faceYaw(dx,dz); const ph=N.t*6.5; A.legL.rotation.x=Math.sin(ph)*0.5; A.legR.rotation.x=-Math.sin(ph)*0.5; A.armL.rotation.x=-Math.sin(ph)*0.3; return L<0.35; };
  if(S.st==='patrol'){ if(onTerrace&&S.cd<=0&&dm<9){ S.st='approach'; } return; }
  N.t+=0; A.armR.rotation.x=N.tray.visible?-1.35:-0.4;
  if(S.st==='approach'){ if(!onTerrace){ S.st='patrol'; S.cd=15; return; } if(dm<1.3||walkTo(me.x,me.z,1.3)){ S.st='ask'; S.askT=0; bubble(A,'Kaj bute popili?',7); } return; }
  if(S.st==='ask'){ A.group.rotation.y=faceYaw(me.x-P.x,me.z-P.z); A.legL.rotation.x=A.legR.rotation.x=0; S.askT+=dt; if(dm>5||S.askT>25){ S.st='patrol'; S.cd=25; bubble(A,'Dobro, dođem kasnije.',3); } return; }
  if(S.st==='fetch'){ if(!S.route.length) S.route=cafeRoute('toBar'); const w=S.route[0]; if(walkTo(w[0],w[1],1.6)){ S.route.shift(); if(!S.route.length){ S.st='wait'; S.wt=2.5; const L=npcByName('Lidija'); if(L) bubble(L.A,'Evo, za Valentinu!',3); } } return; }
  if(S.st==='wait'){ S.wt-=dt; A.legL.rotation.x=A.legR.rotation.x=0; if(S.wt<=0){ N.tray.visible=true; S.st='bring'; S.route=cafeRoute('back'); } return; }
  if(S.st==='bring'){ if(S.route.length){ const w=S.route[0]; if(walkTo(w[0],w[1],1.4)) S.route.shift(); return; } if(dm<1.2||walkTo(me.x,me.z,1.4)){ N.tray.visible=false; bubble(A,'Izvolite! Živjeli!',4); serveDrink(S.order); S.st='patrol'; S.cd=70; } return; } }
function serveDrink(i){ const D=DRINKS[i]; if(!D) return; if(COMBAT.armed){ COMBAT.armed=false; document.body.classList.remove('armed'); } makeGlass(D.g); COMBAT.drink={D,t:0}; GLASS.visible=true; UI.toast('Valentina donosi: '+D.n); }
