/* ===================== GTA sloj: novac, misije, policija, hitna, promet, helikopter ===================== */
const GTA={money:500,home:false,wanted:0,wantT:0,mission:null,step:0,stepT:0,dlg:null,done:{},hearts:[],traffic:[],peds:[],chasers:[],amb:[],beam:null,heli:null,remoteHeli:new Map(),ready:false};
try{ const raw=localStorage.getItem('tuhelj_money'); const m=raw===null?NaN:+raw; if(Number.isFinite(m)&&m>=0) GTA.money=m; GTA.home=localStorage.getItem('tuhelj_home')==='1'; GTA.done=JSON.parse(localStorage.getItem('tuhelj_done')||'{}')||{}; }catch(e){}
function money(d,why){ if(d>0) try{ blip('coin'); }catch(e){} GTA.money=Math.max(0,Math.round(GTA.money+d)); try{ localStorage.setItem('tuhelj_money',String(GTA.money)); }catch(e){} const el=document.getElementById('money'); if(el){ el.textContent='€ '+GTA.money.toLocaleString('hr-HR'); if(d){ el.classList.remove('up','down'); void el.offsetWidth; el.classList.add(d>0?'up':'down'); } } if(d&&why) UI.toast((d>0?'+':'')+d+' € — '+why); }
const SHOP_POS=()=>[-265,-40.5], CAFE_POS=()=>{ const C=LANDMARKS.cafeF; if(!C) return [-224,-44]; const p=C.f(5.0,0,6.5); return [p[0],p[2]]; };
function nearPt(p,r){ return p&&Math.hypot(PLAYER.pos.x-p[0],PLAYER.pos.z-p[1])<r; }
/* ---- shop & home ---- */
const SHOP=[{n:'Sendvič',p:3,hp:35},{n:'Burek',p:4,hp:50},{n:'Voda',p:1,hp:10},{n:'Sok',p:2,hp:15},{n:'Kutija prve pomoći',p:15,hp:100}];
function openShop(){ const el=document.getElementById('shopmenu'); if(!el) return; const list=document.getElementById('shoplist'); list.replaceChildren(...SHOP.map((it,i)=>{ const b=document.createElement('button'); b.className='drink'; const n=document.createElement('span'); n.textContent=it.n+'  (+'+it.hp+' ❤)'; const p=document.createElement('b'); p.textContent=it.p+' €'; b.append(n,p); b.addEventListener('click',()=>buyItem(i)); return b; })); el.classList.add('on'); COMBAT.menuOpen=true; PLAYER.enabled=false; if(document.pointerLockElement) document.exitPointerLock(); }
function closeShop(){ document.getElementById('shopmenu').classList.remove('on'); COMBAT.menuOpen=false; PLAYER.enabled=true; if(!GAME.touch&&!GAME.dragLook){ try{ GAME.renderer.domElement.requestPointerLock(); }catch(e){} } }
function buyItem(i){ const it=SHOP[i]; if(GTA.money<it.p){ UI.toast('Nemaš dovoljno novca'); return; } money(-it.p); COMBAT.hp=Math.min(100,COMBAT.hp+it.hp); updateCombatHUD(); UI.toast('Kupio si: '+it.n+' (+'+it.hp+' ❤)'); }
const HOME_POS=()=>LANDMARKS.apt?[LANDMARKS.apt.x,LANDMARKS.apt.z]:null;
function homeAction(){ if(!GTA.home){ if(GTA.money<800){ UI.toast('Stan Kod Ruže košta 800 € — skupi novac misijama'); return; } money(-800,'kupio si stan Kod Ruže'); GTA.home=true; try{ localStorage.setItem('tuhelj_home','1'); }catch(e){} UI.toast('🏠 Stan Kod Ruže je tvoj! Ovdje se budiš i odmaraš.'); return; } COMBAT.hp=100; COMBAT.bac=0; updateCombatHUD(); UI.toast('😴 Odmorio si se — puno zdravlje'); }
/* ---- health hearts ---- */
function heartsInit(){ const pts=[[-250,-60],[-300,20],[-190,-30],[-130,-55],[-320,-60],[-200,-200]]; const sh=new THREE.Shape(); sh.moveTo(0,0.25); sh.bezierCurveTo(0,0.5,-0.45,0.5,-0.45,0.2); sh.bezierCurveTo(-0.45,-0.05,0,-0.2,0,-0.45); sh.bezierCurveTo(0,-0.2,0.45,-0.05,0.45,0.2); sh.bezierCurveTo(0.45,0.5,0,0.5,0,0.25);
  const geo=new THREE.ExtrudeGeometry(sh,{depth:0.14,bevelEnabled:true,bevelThickness:0.04,bevelSize:0.04,bevelSegments:2}); geo.center(); const mat=new THREE.MeshStandardMaterial({color:0xe5233b,emissive:0x7a0010,roughness:0.35,metalness:0.1});
  for(const [x,z] of pts){ const m=new THREE.Mesh(geo,mat); m.scale.setScalar(0.9); GAME.scene.add(m); GTA.hearts.push({m,x,z,t:0,cd:0}); } }
function heartsTick(dt){ for(const H of GTA.hearts){ H.t+=dt; if(H.cd>0){ H.cd-=dt; H.m.visible=false; continue; } H.m.visible=true; H.m.position.set(H.x,groundAt(H.x,H.z)+1.1+Math.sin(H.t*2)*0.15,H.z); H.m.rotation.y=H.t*1.8;
    if(!COMBAT.dead&&Math.hypot(PLAYER.pos.x-H.x,PLAYER.pos.z-H.z)<1.3&&COMBAT.hp<100){ COMBAT.hp=Math.min(100,COMBAT.hp+50); updateCombatHUD(); H.cd=60; UI.toast('❤ +50 zdravlja'); } } }
/* ---- dialogue ---- */
function sayDialog(lines,done){ GTA.dlg={lines,i:0,done}; showDlg(); }
function showDlg(){ const el=document.getElementById('dlg'); const D=GTA.dlg; if(!D){ el.classList.remove('on'); return; } const [who,txt]=D.lines[D.i]; el.querySelector('.who').textContent=who; el.querySelector('.txt').textContent=txt; el.classList.add('on'); }
function nextDlg(){ const D=GTA.dlg; if(!D) return; D.i++; if(D.i>=D.lines.length){ GTA.dlg=null; showDlg(); if(D.done) D.done(); } else showDlg(); }
/* ---- waypoint beam + indicator ---- */
function setWay(p){ if(!GTA.beam){ const m=new THREE.Mesh(new THREE.CylinderGeometry(1.4,1.4,60,20,1,true),new THREE.MeshBasicMaterial({color:0xffd24a,transparent:true,opacity:0.22,side:THREE.DoubleSide,depthWrite:false})); GAME.scene.add(m); GTA.beam=m; } GTA.way=p; GTA.beam.visible=!!p; if(p) GTA.beam.position.set(p[0],getHeight(p[0],p[1])+30,p[1]); }
/* ---- missions ---- */
function npcPos(n){ const N=npcByName(n); if(N) return [N.A.group.position.x,N.A.group.position.z]; const V=LIFE.villagers.find(v=>v.n===n); return V?[V.A.group.position.x,V.A.group.position.z]:null; }
const MISSIONS=[
 {id:'dostava',giver:'Lidija',title:'Dostava za Putnika',reward:200,
  intro:[['Lidija','Joj, nestalo nam je vina za gemišt, a dečki su žedni!'],['Lidija','Uzmi auto, pokupi kutiju vina kod trgovine i brzo je dovezi ovamo pred kafić.']],
  steps:[{t:'Uđi u bilo koji auto',ok:()=>!!PLAYER.driving},{t:'Pokupi kutiju vina kod trgovine',at:SHOP_POS,r:7,car:true},{t:'Dovezi vino pred kafić (2 min)',at:CAFE_POS,r:8,car:true,time:120}],
  outro:[['Lidija','Ti si zlato! Evo ti 200 eura. Kenka i Jovo ti duguju rundu!'],['Kenka','Živio! Lidija, daj još rundu!']]},
 {id:'taksi',giver:'Poljanec Martin',title:'Taksi za Martina',reward:150,
  intro:[['Poljanec Martin','Ajoj, noga me opet boli, a moram do crkve na misu.'],['Poljanec Martin','Bi me povezel? Dovezi auto do mene.']],
  steps:[{t:'Uđi u auto i dovezi ga do Martina',at:()=>npcPos('Poljanec Martin'),r:6,car:true,onDone:()=>{ GTA.pax='Poljanec Martin'; }},{t:'Odvezi Martina do crkve',at:()=>LANDMARKS.churchDoor?[LANDMARKS.churchDoor.x,LANDMARKS.churchDoor.z]:null,r:10,car:true,onDone:()=>{ GTA.pax=null; }}],
  outro:[['Poljanec Martin','Hvala ti, sinko! Evo ti 150 eura za benzin. Bog te blagoslovil!']]},
 {id:'pozar',giver:'Vatrogasac Krtek',title:'Gori u selu!',reward:300,
  intro:[['Vatrogasac Krtek','Uzbuna! Dojavili su požar u selu!'],['Vatrogasac Krtek','Sjedaj u vatrogasni kamion, ugasi vatru i vrati kamion pred DVD.']],
  steps:[{t:'Sjedni u vatrogasni kamion',ok:()=>PLAYER.driving&&PLAYER.driving.truck,onStart:()=>{ if(!LIFE.fire) startFire(); }},{t:'Ugasi požar (drži G / 💧)',ok:()=>!LIFE.fire},{t:'Vrati kamion pred DVD',at:()=>LANDMARKS.fire?[LANDMARKS.fire.x,LANDMARKS.fire.z]:null,r:12,car:true}],
  outro:[['Vatrogasac Krtek','Bravo! Pravi si vatrogasac. Evo 300 eura od DVD-a Tuhelj!']]},
 {id:'utrka',giver:'Prgac',title:'Utrka formulom',reward:400,
  intro:[['Prgac','Kladim se da ne možeš obići selo formulom za minutu i pol!'],['Prgac','Sjedni u crvenu formulu i prođi kroz sve kontrolne točke.']],
  steps:[{t:'Sjedni u formulu',ok:()=>PLAYER.driving&&PLAYER.driving.formula,onStart:()=>{ const v=DRIVE.find(q=>q.formula); GTA.cps=v?roadPath(v.st.x,v.st.z,900,0).filter((p,i)=>i%45===44).slice(0,5):[]; }},{t:'Kontrolne točke',race:true,time:90}],
  outro:[['Prgac','Ma nemoj! Pobijedio si. Evo 400 eura, pošteno je pošteno.']]},
 {id:'banda',giver:'Šemso',title:'Banda Crni Vukovi',reward:350,
  intro:[['Šemso','Bježi! Banda Crni Vukovi me jurila po cijelom selu!'],['Šemso','Sad su krenuli na tebe — pobjegni im autom i skloni se daleko.']],
  steps:[{t:'Uđi u auto',ok:()=>!!PLAYER.driving},{t:'Pobjegni bandi (budi 150 m daleko 8 s)',escape:true,time:150,onStart:()=>spawnChaser('banda')}],
  outro:[['Šemso','Uf, izgubili su te! Evo ti 350 eura, spasio si mi bicikl.']]}];
function missionAvail(M){ return !GTA.mission&&!GTA.dlg; }
function startMission(M){ sayDialog(M.intro,()=>{ GTA.mission=M; GTA.step=0; GTA.stepT=0; GTA.cp=0; beginStep(); banner(M.title.toUpperCase(),'MISIJA'); }); }
function beginStep(){ const M=GTA.mission, S=M.steps[GTA.step]; GTA.stepT=0; if(S.onStart) S.onStart(); GTA.escT=0; }
function finishStep(){ const M=GTA.mission, S=M.steps[GTA.step]; if(S.onDone) S.onDone(); GTA.step++; if(GTA.step>=M.steps.length){ setWay(null); const R=M.reward; GTA.mission=null; GTA.done[M.id]=(GTA.done[M.id]||0)+1; try{ localStorage.setItem('tuhelj_done',JSON.stringify(GTA.done)); }catch(e){} for(const C of GTA.chasers.filter(c=>c.kind==='banda')) C.leave=true; banner('MISIJA USPJELA','+'+R+' €','#6fe08a'); sayDialog(M.outro,()=>money(R,'misija "'+M.title+'" završena')); return; } beginStep(); }
function failMission(why){ const M=GTA.mission; GTA.mission=null; GTA.pax=null; setWay(null); for(const C of GTA.chasers.filter(c=>c.kind==='banda')) C.leave=true; banner('MISIJA NIJE USPJELA',why,'#e5483b'); }
function missionTick(dt){ const M=GTA.mission; const obj=document.getElementById('objective'); if(!M){ if(obj) obj.style.display='none'; return; } const S=M.steps[GTA.step]; GTA.stepT+=dt; let txt=S.t, target=null;
  if(S.time&&GTA.stepT>S.time){ failMission('isteklo vrijeme'); return; }
  if(S.race){ const cps=GTA.cps||[]; if(!PLAYER.driving||!PLAYER.driving.formula){ failMission('izašao si iz formule'); return; } const p=cps[GTA.cp]; if(!p){ finishStep(); return; } target=p; txt='Kontrolna točka '+(GTA.cp+1)+'/'+cps.length; if(nearPt(p,10)){ GTA.cp++; UI.toast('✔ Točka '+GTA.cp+'/'+cps.length); } }
  else if(S.escape){ const C=GTA.chasers.find(c=>c.kind==='banda'); if(C){ const d=Math.hypot(C.st.x-PLAYER.pos.x,C.st.z-PLAYER.pos.z); if(d>150){ GTA.escT+=dt; txt='Pobjegni bandi — još '+Math.max(0,Math.ceil(8-GTA.escT))+' s'; if(GTA.escT>=8){ finishStep(); return; } } else { GTA.escT=0; txt='Pobjegni bandi! ('+Math.round(d)+' m)'; } } }
  else if(S.at){ target=S.at(); if(target&&nearPt(target,S.r)&&(!S.car||PLAYER.driving)){ finishStep(); return; } }
  else if(S.ok&&S.ok()){ finishStep(); return; }
  setWay(target); if(obj){ obj.style.display='block'; const d=target?Math.round(Math.hypot(target[0]-PLAYER.pos.x,target[1]-PLAYER.pos.z)):null; obj.innerHTML=''; const h=document.createElement('b'); h.textContent=M.title; const t=document.createElement('div'); t.textContent='CILJ: '+txt+(d!==null?'  ·  '+d+' m':'')+(S.time?'  ·  ⏱ '+Math.max(0,Math.ceil(S.time-GTA.stepT))+' s':''); obj.append(h,t); } }
function giverNear(){ if(GTA.mission||GTA.dlg||PLAYER.driving||PKC.sit) return null; for(const M of MISSIONS){ const p=npcPos(M.giver); if(p&&nearPt(p,3.2)) return M; } return null; }
function giverMarks(){ if(!GTA.marks){ GTA.marks=new Map(); } for(const M of MISSIONS){ let A=null; const N=npcByName(M.giver); if(N) A=N.A; else { const V=LIFE.villagers.find(v=>v.n===M.giver); if(V) A=V.A; } if(!A) continue; let mk=GTA.marks.get(M.id); if(!mk){ const c=cvs(128,128), g=c.getContext('2d'); g.fillStyle='#ffd24a'; g.beginPath(); g.arc(64,64,58,0,TAU); g.fill(); g.fillStyle='#161616'; g.font='900 86px Manrope, Arial'; g.textAlign='center'; g.textBaseline='middle'; g.fillText('!',64,70); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; mk=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true})); mk.scale.set(0.55,0.55,1); mk.renderOrder=24; A.group.add(mk); GTA.marks.set(M.id,mk); } mk.position.y=(A.bubY||2.62)+0.55; mk.visible=!GTA.mission&&!GTA.dlg; } }
/* ---- AI drivers: police, gang, ambulance ---- */
function makeAI(kind){ const col=kind==='policija'?'#f4f4f4':kind==='banda'?'#141414':'#f7f7f7'; const v=makeCarGroup(kind==='hitna'?'van':kind==='policija'?'police':kind==='banda'?'sport':'sedan',col); const bar=new THREE.Group(); const L=[]; for(const sd of [-1,1]){ const m=new THREE.Mesh(new THREE.BoxGeometry(0.3,0.1,0.18),new THREE.MeshBasicMaterial({color:kind==='banda'?0x220000:(sd<0?0x1f5fff:0xff2a2a)})); m.position.set(-0.2,(kind==='hitna'?2.05:(v.roofY?v.roofY+0.03:1.55)),sd*0.22); bar.add(m); L.push(m); } if(kind!=='banda') v.group.add(bar);
  if(kind!=='banda'){ const c=cvs(512,96), g=c.getContext('2d'); g.fillStyle=kind==='policija'?'#1f3f8f':'#c8161d'; g.fillRect(0,0,512,96); g.fillStyle='#fff'; g.font='900 64px Manrope, Arial'; g.textAlign='center'; g.fillText(kind==='policija'?'POLICIJA':'HITNA',256,70); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; for(const sd of [-1,1]){ const p=new THREE.Mesh(new THREE.PlaneGeometry(1.6,0.3),new THREE.MeshBasicMaterial({map:t})); p.position.set(0,0.8,sd*(v.wid/2+0.01)); p.rotation.y=sd>0?0:Math.PI; v.group.add(p); } }
  GAME.scene.add(v.group); return {v,kind,L,st:{x:0,z:0,yaw:0,v:0,steer:0,y:0,pitch:0,roll:0,spin:0},t:0}; }
function spawnNear(C,dist){ const a=Math.random()*TAU; let x=PLAYER.pos.x+Math.cos(a)*dist, z=PLAYER.pos.z+Math.sin(a)*dist; const n=nearestRoad(x,z,60); if(n){ x=n.s.x; z=n.s.z; } C.st.x=x; C.st.z=z; C.st.yaw=faceYaw(PLAYER.pos.x-x,PLAYER.pos.z-z); }
function spawnChaser(kind){ const C=makeAI(kind); spawnNear(C,kind==='banda'?60:90); if(kind==='banda'){ const nm=new THREE.Sprite(new THREE.SpriteMaterial({map:tagTex('Crni Vukovi','#e5483b'),transparent:true})); nm.scale.set(3.4,0.42,1); nm.position.y=2.3; C.v.group.add(nm); } GTA.chasers.push(C); return C; }
function spawnAmbulance(x,z){ const C=makeAI('hitna'); C.target=[x,z]; C.st.x=x+60; C.st.z=z+20; const n=nearestRoad(C.st.x,C.st.z,80); if(n){ C.st.x=n.s.x; C.st.z=n.s.z; } GTA.amb.push(C); UI.toast('🚑 Hitna je na putu'); }
function driveAI(C,tx,tz,maxV,dt){ const s=C.st; if(C.wreck||C.burnT>0){ s.v=0; s.steer=0; C.v.st=s; poseVehicle(C.v); return 1e9; } const dx=tx-s.x, dz=tz-s.z, d=Math.hypot(dx,dz); const want=faceYaw(dx,dz); let dh=want-s.yaw; while(dh>Math.PI) dh-=TAU; while(dh<-Math.PI) dh+=TAU; s.yaw+=Math.max(-1.6*dt,Math.min(1.6*dt,dh)); const tv=(d<6?0:Math.min(maxV,d*0.8))*(1-Math.min(0.65,Math.abs(dh)*0.5)); s.v+=(tv-s.v)*Math.min(1,dt*(tv<s.v?2.5:1.5));
  s.x+=-Math.sin(s.yaw)*s.v*dt; s.z+=-Math.cos(s.yaw)*s.v*dt; const q={x:s.x,z:s.z}; carCollide(q,1.0,getHeight(s.x,s.z)+0.6); s.x=q.x; s.z=q.z; s.steer=Math.max(-0.5,Math.min(0.5,dh)); s.spin+=s.v*dt/0.33; C.v.st=s; poseVehicle(C.v); C.t+=dt; const on=Math.floor(C.t*6)%2===0; if(C.L.length){ C.L[0].visible=on; C.L[1].visible=!on; } return d; }
function aiTick(dt){ // wanted level decay + police
  if(GTA.wanted>0&&!GTA.warned){ GTA.warned=true; UI.toast('🚓 Policija te traži!'); } if(!GTA.wanted&&GTA.warned){ GTA.warned=false; UI.toast('Policija te više ne traži'); }
  for(let i=GTA.chasers.length-1;i>=0;i--){ const C=GTA.chasers[i]; if(C.wreck||C.burnT>0){ driveAI(C,0,0,0,dt); if(C.gone){ GAME.scene.remove(C.v.group); GTA.chasers.splice(i,1); if(typeof lawCarGone==='function') lawCarGone(C); } continue; } const leave=C.leave||(C.kind==='policija'&&GTA.wanted===0); const d=Math.hypot(C.st.x-PLAYER.pos.x,C.st.z-PLAYER.pos.z);
    if(leave){ C.away=(C.away||0)+dt; driveAI(C,C.st.x-Math.sin(C.st.yaw)*60,C.st.z-Math.cos(C.st.yaw)*60,18,dt); if(C.away>6||d>180){ GAME.scene.remove(C.v.group); GTA.chasers.splice(i,1); } continue; }
    if(C.kind==='policija'&&C.tgt){ if(C.wander&&Math.hypot(C.tgt[0]-C.st.x,C.tgt[1]-C.st.z)<12){ C.tgt=[C.tgt[0]+(Math.random()-0.5)*80,C.tgt[1]+(Math.random()-0.5)*80]; COP.last=C.tgt; } const w=routeTo(C,C.tgt[0],C.tgt[1],dt); driveAI(C,w[0],w[1],C.wander?13:22,dt); } else if(C.wait&&d>110){ driveAI(C,C.st.x,C.st.z,0,dt); } else { C.wait=false; const w=routeTo(C,PLAYER.pos.x,PLAYER.pos.z,dt); driveAI(C,w[0],w[1],C.kind==='banda'?24:22,dt); }
    if(d<4.2){ C.close=(C.close||0)+dt; if(C.kind==='policija'&&C.close>1.2&&COP.state==='CHASE'&&PLAYER.driving&&Math.abs(PLAYER.driving.st.v)<1.5&&GTA.wanted<=2){ busted(); } if(C.kind==='banda'&&C.close>0.5){ C.close=0; takeDamage(8,'banda'); if(PLAYER.driving) PLAYER.driving.st.v*=0.6; } } else C.close=0; }
  for(let i=GTA.amb.length-1;i>=0;i--){ const A=GTA.amb[i]; A.life=(A.life||0)+dt; if(A.busy){ A.life=Math.min(A.life,40); driveAI(A,A.st.x,A.st.z,0,dt); continue; } const tg=A.leaving||A.target; const w=routeTo(A,tg[0],tg[1],dt); driveAI(A,w[0],w[1],16,dt); const d=Math.hypot(tg[0]-A.st.x,tg[1]-A.st.z); if(!A.leaving&&d<8) A.wait=(A.wait||0)+dt; if(A.wait>12||A.life>70||(A.leaving&&d<12)||A.gone){ GAME.scene.remove(A.v.group); GTA.amb.splice(i,1); } }
  const w=document.getElementById('wanted'); if(w){ w.textContent=GTA.wanted?'★'.repeat(GTA.wanted)+'☆'.repeat(5-GTA.wanted):''; w.style.display=GTA.wanted?'block':'none'; } }
function crime(n){ GTA.wanted=Math.min(5,GTA.wanted+n); GTA.wantT=0; }
function busted(){ GTA.wanted=0; COP.state='RETURN'; for(const C of GTA.chasers) if(C.kind==='policija') C.leave=true; if(PLAYER.driving) exitCar(); money(-100,'uhićen si — kazna'); UI.toast('🚔 UHIĆEN! Kazna 100 €'); if(GTA.mission) failMission('uhitila te policija'); const s=SPAWNS[0]; teleport(s[0],s[1]); }
/* ---- traffic and pedestrians ---- */
function trafficInit(){ const starts=[[-395,6],[-258,-46],[-150,-30],[-300,-70],[-200,-160],[-330,40]]; const cols=['#c8c8c8','#2a4f8a','#8a2a2a','#e8e2d0','#3a3a3a','#6b8a3a']; const types=['hatch','sedan','suv','hatch','sedan','van'];
  starts.forEach((p,i)=>{ const path=roadPath(p[0],p[1],380,0); if(path.length<12) return; const v=makeCarGroup(types[i],cols[i]); GAME.scene.add(v.group); GTA.traffic.push({v,path,u:Math.random()*(path.length-2),dir:1,sp:8+Math.random()*3,st:{x:0,z:0,yaw:0,v:0,steer:0,y:0,pitch:0,roll:0,spin:0}}); });
  const names=['Štefica','Dragica','Mirko','Ivek','Barica','Joža st.']; const cols2=['#b8324a','#6b3a8a','#2a6b5a','#8a6b2a','#3a5a8a','#5a5a5a'];
  names.forEach((n,i)=>{ const s=[[-270,-30],[-240,-70],[-300,-10],[-180,-45],[-320,-50],[-210,-20]][i]; const path=roadPath(s[0],s[1],140,0.66); if(path.length<6) return; const A=makePerson(n,cols2[i],i%2===0?{female:true,hair:0x6a4a2a,skirt:0x3a2a3a}:{}); GAME.scene.add(A.group); GTA.peds.push({A,path,u:Math.random()*(path.length-2),dir:1,sp:0.9+Math.random()*0.4,t:Math.random()*9}); }); }
function trafficTick(dt){ const me=PLAYER.pos; for(const T of GTA.traffic){ if(T.wreck||T.burnT>0){ T.st.v=0; T.v.st=T.st; poseVehicle(T.v); continue; } const P=T.path; const i=Math.floor(T.u), k=T.u-i; const a=P[Math.max(0,Math.min(P.length-1,i))], b=P[Math.max(0,Math.min(P.length-1,i+T.dir))]; const x=a[0]+(b[0]-a[0])*k*T.dir*0+ (b[0]-a[0])*0, z=0;
    const px=P[i][0]+(P[Math.min(P.length-1,i+1)][0]-P[i][0])*k, pz=P[i][1]+(P[Math.min(P.length-1,i+1)][1]-P[i][1])*k; const fx=(P[Math.min(P.length-1,i+1)][0]-P[i][0])*T.dir, fz=(P[Math.min(P.length-1,i+1)][1]-P[i][1])*T.dir;
    const ahead=Math.hypot(me.x-(px+fx*1.5),me.z-(pz+fz*1.5)); let blocked=ahead<7; for(const C of DRIVE){ if(Math.hypot(C.st.x-(px+fx*1.8),C.st.z-(pz+fz*1.8))<5) blocked=true; }
    const tv=blocked?0:T.sp; T.st.v+=(tv-T.st.v)*Math.min(1,dt*2); T.u+=T.st.v*dt/4*T.dir; if(T.u>=P.length-1.01){ T.u=P.length-1.02; T.dir=-1; } if(T.u<=0){ T.u=0.01; T.dir=1; }
    const fl=Math.hypot(fx,fz)||1; const lane=2.1; T.st.x=px+(-fz/fl)*lane; T.st.z=pz+(fx/fl)*lane; T.st.yaw=faceYaw(fx,fz); T.st.spin+=T.st.v*dt/0.33; T.v.st=T.st; poseVehicle(T.v); }
  for(const Q of GTA.peds){ Q.t+=dt; const P=Q.path; const near=Math.hypot(me.x-Q.A.group.position.x,me.z-Q.A.group.position.z)<1.6; if(!near){ Q.u+=dt*Q.sp*Q.dir/4; } if(Q.u>=P.length-1.01){ Q.u=P.length-1.02; Q.dir=-1; } if(Q.u<=0){ Q.u=0.01; Q.dir=1; }
    const i=Math.floor(Q.u), k=Q.u-i; const a=P[i], b=P[Math.min(P.length-1,i+1)]; const x=a[0]+(b[0]-a[0])*k, z=a[1]+(b[1]-a[1])*k; Q.A.group.position.set(x,groundAt(x,z),z); Q.A.group.rotation.y=faceYaw((b[0]-a[0])*Q.dir,(b[1]-a[1])*Q.dir); const ph=Q.t*5.5*(near?0:1); Q.A.legL.rotation.x=Math.sin(ph)*0.45; Q.A.legR.rotation.x=-Math.sin(ph)*0.45; Q.A.armL.rotation.x=-Math.sin(ph)*0.3; Q.A.armR.rotation.x=Math.sin(ph)*0.3; } }
/* ---- helicopter ---- */
function makeHeli(){ const g=new THREE.Group(); const M=(c,m=0.4,r=0.4)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r}); const body=new THREE.Mesh(new THREE.SphereGeometry(1.2,20,14),M(0xc8161d,0.5,0.3)); body.scale.set(1.7,1,1); body.position.y=1.5; body.castShadow=true; g.add(body);
  const glass=new THREE.Mesh(new THREE.SphereGeometry(0.95,16,12,0,Math.PI,0,Math.PI/2),M(0x223344,0.8,0.1)); glass.rotation.set(0,Math.PI/2,-0.5); glass.position.set(1.05,1.75,0); g.add(glass);
  const boom=new THREE.Mesh(new THREE.CylinderGeometry(0.16,0.3,4.2,10),M(0xc8161d,0.5,0.3)); boom.rotation.z=Math.PI/2; boom.position.set(-3.4,1.75,0); g.add(boom); const fin=new THREE.Mesh(new THREE.BoxGeometry(0.6,1.0,0.08),M(0xf4f2ea)); fin.position.set(-5.3,2.2,0); g.add(fin);
  for(const sz of [-0.8,0.8]){ const sk=new THREE.Mesh(new THREE.CylinderGeometry(0.06,0.06,3.2,8),M(0x2a2a2a,0.7,0.4)); sk.rotation.z=Math.PI/2; sk.position.set(0,0.1,sz); g.add(sk); for(const x of [-0.7,0.7]){ const st=new THREE.Mesh(new THREE.CylinderGeometry(0.04,0.04,0.6,6),M(0x2a2a2a)); st.position.set(x,0.4,sz*0.9); g.add(st); } }
  const rot=new THREE.Group(); rot.position.set(0,2.75,0); for(let k=0;k<2;k++){ const b=new THREE.Mesh(new THREE.BoxGeometry(9.5,0.04,0.3),M(0x1a1a1a,0.5,0.5)); b.rotation.y=k*Math.PI/2; rot.add(b); } g.add(rot); const mast=new THREE.Mesh(new THREE.CylinderGeometry(0.08,0.08,0.5,8),M(0x333333)); mast.position.y=2.5; g.add(mast);
  const tr=new THREE.Group(); tr.position.set(-5.45,2.2,0.12); const tb=new THREE.Mesh(new THREE.BoxGeometry(1.3,0.12,0.03),M(0x1a1a1a)); tr.add(tb); g.add(tr);
  { const c=cvs(256,64), x=c.getContext('2d'); x.fillStyle='#fff'; x.font='900 44px Manrope, Arial'; x.textAlign='center'; x.fillText('9A-TUH',128,48); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; for(const sd of [-1,1]){ const p=new THREE.Mesh(new THREE.PlaneGeometry(1.4,0.35),new THREE.MeshBasicMaterial({map:t,transparent:true})); p.position.set(-2.4,1.8,sd*0.29); p.rotation.y=sd>0?0:Math.PI; g.add(p); } }
  return {g,rot,tr,st:{x:0,y:0,z:0,yaw:0,vx:0,vy:0,vz:0,pitch:0,roll:0,spin:0}}; }
function heliInit(){ if(GTA.heli) return; const l=LAND.find(q=>q.t==='pitch'); let x=-150, z=-60; if(l){ const bb=polyBBox(l.P); x=(bb[0]+bb[1])/2; z=(bb[2]+bb[3])/2; } else if(LANDMARKS.fire){ x=LANDMARKS.fire.x+8; z=LANDMARKS.fire.z+8; } const H=makeHeli(); H.st.x=x; H.st.z=z; H.st.y=getHeight(x,z)+0.05; GAME.scene.add(H.g); GTA.heli=H; heliPose(H); }
function heliPose(H){ const s=H.st; H.g.position.set(s.x,s.y,s.z); H.g.rotation.set(0,s.yaw+Math.PI/2,0); H.g.rotateZ(s.pitch); H.g.rotateX(s.roll); H.rot.rotation.y=s.spin; H.tr.rotation.z=s.spin*2.5; }
function nearHeli(){ const H=GTA.heli; return H&&!PLAYER.heli&&!PLAYER.driving&&Math.hypot(PLAYER.pos.x-H.st.x,PLAYER.pos.z-H.st.z)<4.5; }
function enterHeli(){ PLAYER.heli=GTA.heli; COMBAT.armed=false; document.body.classList.remove('armed'); document.body.classList.add('driving'); CARCAM.init=false; UI.toast('🚁 Helikopter: W/S naprijed-nazad, A/D okret, Space gore, C dolje (mobitel: krug + ▲▼)'); }
function exitHeli(){ const H=PLAYER.heli; if(!H) return; if(H.st.y-getHeight(H.st.x,H.st.z)>1.5){ UI.toast('Prvo sleti na tlo'); return; } PLAYER.heli=null; document.body.classList.remove('driving'); teleport(H.st.x+3,H.st.z+1); }
function heliTick(dt){ const H=PLAYER.heli; if(!H) return; const s=H.st; const fwd=(KEYS.KeyW||KEYS.ArrowUp?1:0)-(KEYS.KeyS||KEYS.ArrowDown?1:0)+(-(TOUCH.mz||0)); const turn=(KEYS.KeyA||KEYS.ArrowLeft?1:0)-(KEYS.KeyD||KEYS.ArrowRight?1:0)+(-(TOUCH.mx||0)); const up=(KEYS.Space||TOUCH.up||TOUCH.jump?1:0)-(KEYS.KeyC||KEYS.ControlLeft||TOUCH.down?1:0); TOUCH.jump=false;
  const gy=getHeight(s.x,s.z); const air=s.y-gy>0.2; s.spin+=dt*(air||up>0?26:14); s.yaw+=Math.max(-1,Math.min(1,turn))*1.3*dt*(air?1:0.3);
  const f=Math.max(-1,Math.min(1,fwd)); const ax=-Math.sin(s.yaw)*f*16, az=-Math.cos(s.yaw)*f*16; s.vx+=(air?ax:0)*dt; s.vz+=(air?az:0)*dt; s.vx*=Math.exp(-dt*0.8); s.vz*=Math.exp(-dt*0.8); const sp=Math.hypot(s.vx,s.vz); if(sp>48){ s.vx*=48/sp; s.vz*=48/sp; }
  s.vy+=(up*9-s.vy*1.8)*dt; s.x+=s.vx*dt; s.z+=s.vz*dt; s.y+=s.vy*dt; const hb=BHASH.hit(s.x,s.z,1.5); if(hb&&s.y<hb.y1+0.3){ s.y=Math.max(s.y,hb.y1+0.3); s.vy=Math.max(0,s.vy); } if(s.y<gy+0.05){ s.y=gy+0.05; s.vy=Math.max(0,s.vy); s.vx*=0.8; s.vz*=0.8; } s.y=Math.min(s.y,gy+180);
  s.pitch+=((air?-f*0.22:0)-s.pitch)*Math.min(1,dt*3); s.roll+=((air?-turn*0.15:0)-s.roll)*Math.min(1,dt*3); heliPose(H); PLAYER.pos.set(s.x,s.y,s.z); const spd=document.getElementById('speedo'); if(spd) spd.textContent=Math.round(sp*3.6)+' km/h · '+Math.round(s.y-gy)+' m'; }
function heliCamera(cam,dt){ const s=PLAYER.heli.st; const yaw=s.yaw+CARCAM.orbit; const tx=s.x+Math.sin(yaw)*13, tz=s.z+Math.cos(yaw)*13, ty=s.y+5.5; const k=1-Math.exp(-dt*6); if(!CARCAM.init){ cam.position.set(tx,ty,tz); CARCAM.init=true; } else { cam.position.x+=(tx-cam.position.x)*k; cam.position.y+=(ty-cam.position.y)*k; cam.position.z+=(tz-cam.position.z)*k; } cam.lookAt(s.x,s.y+1.5,s.z); if(cam.fov!==72){ cam.fov=72; cam.updateProjectionMatrix(); } }
function remoteHeliTick(){ for(const R of NET.remotes.values()){ let H=GTA.remoteHeli.get(R.id); if(Array.isArray(R.hl)){ if(!H){ H=makeHeli(); GAME.scene.add(H.g); GTA.remoteHeli.set(R.id,H); } H.st.x+=(R.hl[0]-H.st.x)*0.2; H.st.y+=(R.hl[1]-H.st.y)*0.2; H.st.z+=(R.hl[2]-H.st.z)*0.2; H.st.yaw=R.hl[3]; H.st.spin+=0.4; heliPose(H); if(R.av) R.av.group.visible=false; } else if(H){ GAME.scene.remove(H.g); GTA.remoteHeli.delete(R.id); } }
  if(GTA.heli) GTA.heli.g.visible=true; }
/* ---- per-frame ---- */
function gtaTick(dt){ if(!GTA.ready){ GTA.ready=true; money(0); heartsInit(); trafficInit(); heliInit(); }
  try{ heartsTick(dt); missionTick(dt); aiTick(dt); trafficTick(dt); giverMarks(); remoteHeliTick(); if(!PLAYER.heli&&GTA.heli){ heliPose(GTA.heli); if(GTA.heli.st.y-getHeight(GTA.heli.st.x,GTA.heli.st.z)>0.1){ GTA.heli.st.y-=dt*4; } } }catch(e){ console.warn('gta',e); }
  const pb=document.getElementById('gtabtn'); if(pb){ const g=giverNear(); const ss=shopSpot(); const txt=g?'❗ '+g.title:nearHeli()?'🚁 Helikopter':intPrompt()?intPrompt():nearPt(HOME_POS(),4)?(GTA.home?'🏠 Odmori se':'🏠 Kupi stan 800 €'):''; pb.classList.toggle('on',!!txt&&!COMBAT.menuOpen); const sp=pb.querySelector('span'); if(sp&&sp.textContent!==txt) sp.textContent=txt; } }
function gtaUse(){ if(GTA.dlg){ nextDlg(); return true; } if(PLAYER.heli){ exitHeli(); return true; } if(PLAYER.driving||PLAYER.riding) return false; const g=giverNear(); if(g){ startMission(g); return true; } if(nearHeli()){ enterHeli(); return true; } if(intUse()) return true; if(nearPt(HOME_POS(),4)){ homeAction(); return true; } return false; }

function nearAnyNPC(r){ const me=PLAYER.pos; const all=[...NPCS.map(n=>n.A),...LIFE.villagers.map(v=>v.A),...GTA.peds.map(q=>q.A)]; return all.some(A=>Math.hypot(A.group.position.x-me.x,A.group.position.z-me.z)<r); }
// shooting only brings the police if a cop is around or someone right next to you sees it (and then they call it in)
function gtaShot(){ if(GAME.time-(GTA.lastCrime||-99)<8) return; const copNear=GTA.chasers.some(c=>c.kind==='policija'&&Math.hypot(c.st.x-PLAYER.pos.x,c.st.z-PLAYER.pos.z)<70); if(copNear||(nearAnyNPC(14)&&Math.random()<0.35)){ crime(1); GTA.lastCrime=GAME.time; } }
function priceOf(D){ const m=String(D.p||'').replace(',','.').match(/[\d.]+/); return m?+m[0]:0; }
