/* ===================== GTA 2: NPC health, shop interior, bicycles, HUD polish ===================== */
function offRoad(x,z,margin){ const n=nearestRoad(x,z,30); if(!n) return [x,z]; const s=n.s; const nx=-s.tz, nz=s.tx; const d=(x-s.x)*nx+(z-s.z)*nz; const need=(s.w||6)/2+(margin||1.2); if(Math.abs(d)>=need) return [x,z]; const sg=d>=0?1:-1; return [x+nx*(need-d*sg)*sg,z+nz*(need-d*sg)*sg]; }
/* ---- every person has health; killing brings police + ambulance ---- */
function allPeople(){ const L=[]; for(const N of NPCS) L.push({A:N.A,n:N.d.n}); for(const V of LIFE.villagers) L.push({A:V.A,n:V.n}); for(const Q of GTA.peds) L.push({A:Q.A,n:Q.A.name||'Mještanin'}); if(typeof PK3!=='undefined'&&PK3&&PK3.npc) for(const [n,A] of PK3.npc) L.push({A,n}); if(typeof LAW!=='undefined') for(const c of LAW.crew) if(c.out) L.push({A:c.A,n:c.A.name,crew:c}); return L; }
function hurtPerson(P,dmg,byMe){ const A=P.A; if(A.dead) return; A.hp=(A.hp===undefined?100:A.hp)-dmg; if(A.hp<=0){ A.dead=true; A.deadT=45; A.deadPos=A.group.position.clone(); A.deadYaw=A.group.rotation.y; A.deadT0=GAME.time; A.knock=(typeof HITDIR!=='undefined'&&HITDIR.lengthSq()>0)?new THREE.Vector3(HITDIR.x,0,HITDIR.z).normalize():new THREE.Vector3(); A.deadY0=A.group.position.y; try{ bloodPool(A); }catch(e){} if(A.bub) A.bub.visible=false; if(byMe) pushFeed(NET.name+' → '+P.n); if(A.noCrime){ if(A.noRevive) A.deadT=1e9; return; } if(byMe) crime(3); try{ spawnAmbulance(A.deadPos.x,A.deadPos.z); }catch(e){} UI.toast('💀 '+P.n+' je pao — policija i hitna dolaze!'); }
  else if(A.bub!==undefined||true){ fleeFrom(A,PLAYER.pos,14); try{ bubble(A,A.noCrime?['Aaa!','Ubijte ga!','Pucaj!'][Math.floor(Math.random()*3)]:['Au!','Kaj delaš?!','Pomoć! Policija!'][Math.floor(Math.random()*3)],2); }catch(e){} if(byMe&&!A.noCrime&&GAME.time-(GTA.lastCrime||-99)>3){ crime(1); GTA.lastCrime=GAME.time; } } }
function peopleRay(o,d,maxT){ let best=null; for(const P of allPeople()){ const A=P.A; if(A.dead||!A.group.visible) continue; const p=A.group.position; const h=rayCyl(o,d,p.x,p.z,p.y-0.1,p.y+1.9,0.36); if(h&&h.t<maxT&&(!best||h.t<best.t)) best={t:h.t,P,head:h.y>p.y+1.55}; } return best; }
function peopleSplash(p,R){ for(const P of allPeople()){ const A=P.A; if(A.dead) continue; const q=A.group.position; const d=Math.hypot(q.x-p.x,q.z-p.z,(q.y+0.9)-p.y); if(d<R) hurtPerson(P,Math.round(110*(1-d/R)+15),true); } }
function peopleTick(dt){ const v=PLAYER.driving; for(const P of allPeople()){ const A=P.A; if(!A.dead&&fleeStep(A,dt)) continue;
    if(A.dead){ A.deadT-=dt; const e=Math.min(1,(GAME.time-(A.deadT0||-9))/0.6), k=e*e*(3-2*e); const kn=A.knock||new THREE.Vector3(); const px=A.deadPos.x+kn.x*1.1*k, pz=A.deadPos.z+kn.z*1.1*k; A.group.position.set(px,(A.deadY0!==undefined?A.deadY0:A.deadPos.y)*(1-k)+(groundAt(px,pz)+0.18)*k,pz);
      /* falls over away from the shot instead of snapping flat */ const back=kn.lengthSq()>0?Math.sign(kn.x*Math.sin(A.deadYaw)+kn.z*Math.cos(A.deadYaw))||1:1; A.group.rotation.set(-back*Math.PI/2*k,A.deadYaw,0); if(A.pool){ const s=Math.min(1,(GAME.time-A.deadT0)/5)*1.1+0.1; A.pool.scale.set(s,s,s); A.pool.position.set(px,groundAt(px,pz)+0.03,pz); } A.legL.rotation.x=A.legR.rotation.x=0; A.armL.rotation.x=A.armR.rotation.x=-0.3; if(A.deadT<=0){ A.dead=false; A.hp=100; A.group.rotation.set(0,A.deadYaw,0); if(A.pool){ GAME.scene.remove(A.pool); A.pool=null; } } continue; }
    if(v&&Math.abs(v.st.v)>7&&!v.formula){ const q=A.group.position; if(Math.hypot(q.x-v.st.x,q.z-v.st.z)<(v.bike?0.9:1.8)&&Math.abs(q.y-v.st.y)<2) hurtPerson(P,Math.abs(v.st.v)*6,true); } } }
/* ---- enterable shop: interior room with shelves, fridges and a cashier ---- */
const SHOPIN={x:-1450,z:-1450,y:260,built:false,inside:false};
function buildShopInterior(){ if(SHOPIN.built) return; SHOPIN.built=true; const {x,z,y}=SHOPIN; const f=frame(x,z,0,0); const cs=new ChunkSet(); const G=cs.get('wall',x,z), Wd=cs.get('wood',x,z), Mt=cs.get('metal',x,z), Gl=cs.get('glow',x,z), Cl=cs.get('cloth',x,z);
  const W=6, D=5, H=3.1; G.box(f,-W,W,y-0.3,y,-D,D,lin('#8e969c')); for(const [a,b,c2,d2] of [[-W,W,-D,-D+0.04],[-W,-W+0.04,-D,D],[W-0.04,W,-D,D]]) G.box(f,a,b,y+1.0,y+1.25,c2,d2,lin('#2e7d4f')); G.box(f,-W,W,y+H,y+H+0.2,-D,D,lin('#f2f1ec'));
  G.box(f,-W-0.2,-W,y,y+H,-D,D,lin('#ece8dd')); G.box(f,W,W+0.2,y,y+H,-D,D,lin('#ece8dd')); G.box(f,-W,W,y,y+H,-D-0.2,-D,lin('#e4e8ec')); G.box(f,-W,-1.0,y,y+H,D,D+0.2,lin('#e4e8ec')); G.box(f,1.0,W,y,y+H,D,D+0.2,lin('#e4e8ec')); G.box(f,-1.0,1.0,y+2.3,y+H,D,D+0.2,lin('#e4e8ec'));
  Wd.box(f,-1.0,1.0,y,y+2.3,D+0.15,D+0.2,lin('#6d5a44')); Cl.box(f,-1.8,1.8,y+0.002,y+0.01,D-1.2,D-0.05,lin('#2f5f3a'));
  for(let i=-2;i<=2;i++) Gl.box(f,i*2.2-0.6,i*2.2+0.6,y+H-0.04,y+H,-0.25,0.25,lin('#fffbe8'));
  const cols=['#c62828','#f2c318','#1e4fb3','#2e8b3a','#e07a1a','#7b2cbf','#f4f2ea','#8a5a36'];
  const shelf=(sx,sz,len,rot)=>{ const sf=frame(x+sx,z+sz,rot,0); Mt.box(sf,-len/2,len/2,y,y+1.9,-0.025,0.025,lin('#8fa3b3')); for(const ex of [-1,1]) Mt.box(sf,ex*len/2-0.03,ex*len/2+0.03,y,y+1.95,-0.32,0.32,lin('#2f6f9a')); Mt.box(sf,-len/2,len/2,y,y+0.12,-0.32,0.32,lin('#2f6f9a'));
    for(let lv=0;lv<4;lv++){ const yy=y+0.25+lv*0.45; Mt.box(sf,-len/2,len/2,yy,yy+0.03,-0.32,0.32,lin('#c9cfd4')); for(let k=0;k<Math.floor(len/0.2);k++){ const px=-len/2+0.11+k*0.2; for(const side of [-1,1]){ const h=0.14+((k*7+lv*3+(side>0?1:0))%5)*0.05; const w=0.07+((k+lv)%3)*0.015; G.box(sf,px-w,px+w,yy+0.03,yy+0.03+h,side>0?0.06:-0.27,side>0?0.27:-0.06,lin(cols[(k+lv*3+(side>0?2:0))%cols.length])); } } } addCollider(x+sx,z+sz,rot,len+0.1,0.7,y-1,y+2); };
  shelf(-3.2,-1.2,4,0); shelf(-3.2,1.4,4,0); shelf(2.6,-2.4,3.6,0);
  for(let k=0;k<3;k++){ const ff=frame(x+W-0.45,z-3.6+k*1.1,Math.PI/2,0); Mt.box(ff,-0.5,0.5,y,y+2.0,-0.35,0.35,lin('#f4f4f2')); Gl.box(ff,-0.44,0.44,y+0.15,y+1.9,0.34,0.36,lin('#dfefff')); for(let lv=0;lv<4;lv++) for(let j=0;j<5;j++) G.box(ff,-0.4+j*0.17,-0.3+j*0.17,y+0.25+lv*0.42,y+0.5+lv*0.42,0.1,0.25,lin(cols[(j+lv+k)%cols.length])); } addCollider(x+W-0.45,z-2.5,0,0.8,3.4,y-1,y+2.1);
  const cf=frame(x+2.6,z+2.2,0,0); Wd.box(cf,-1.3,1.3,y,y+0.95,-0.4,0.4,lin('#7a5a3a')); Mt.box(cf,-1.35,1.35,y+0.95,y+1.0,-0.45,0.45,lin('#3a3d42')); Mt.box(cf,0.6,0.95,y+1.0,y+1.3,-0.2,0.1,lin('#1c1f22')); Mt.box(cf,0.62,0.93,y+1.1,y+1.28,0.1,0.12,lin('#57c7ff')); addCollider(x+2.6,z+2.2,0,2.7,0.9,y-1,y+1.1);
  { const c=cvs(512,128), g=c.getContext('2d'); g.fillStyle='#1d5a33'; g.fillRect(0,0,512,128); g.fillStyle='#fff'; g.font='900 70px Manrope, Arial'; g.textAlign='center'; g.fillText('TRGOVINA',256,90); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; const m=new THREE.Mesh(new THREE.PlaneGeometry(2.4,0.6),new THREE.MeshBasicMaterial({map:t})); m.position.set(x+2.6,y+2.5,z-D+0.02); GAME.scene.add(m); }
  addFloor(frame(x,z,0,0),0,-W,W,-D,D,y); addCollider(x-W-0.1,z,0,0.3,2*D,y-1,y+H); addCollider(x+W+0.1,z,0,0.3,2*D,y-1,y+H); addCollider(x,z-D-0.1,0,2*W,0.3,y-1,y+H); addCollider(x-3.5,z+D+0.1,0,5,0.3,y-1,y+H); addCollider(x+3.5,z+D+0.1,0,5,0.3,y-1,y+H);
  for(const m of cs.meshes(GAME.bm,{cast:false})) GAME.scene.add(m); const A=makePerson('Blagajnica Mira','#2e6b3a',{female:true,apron:true,hair:0x8a5a2a}); A.group.position.set(x+2.6,y,z+1.5); A.group.rotation.y=faceYaw(0,1); GAME.scene.add(A.group); SHOPIN.cashier=A; }
function shopDoorOutside(){ const p=SHOP_POS(); return p; }
function enterShop(){ try{ blip('door'); }catch(e){} buildShopInterior(); SHOPIN.inside=true; SHOPIN.back=[PLAYER.pos.x,PLAYER.pos.z]; teleport(SHOPIN.x,SHOPIN.z+3.8,SHOPIN.x,SHOPIN.z); PLAYER.pos.y=SHOPIN.y; PLAYER.vel.set(0,0,0); try{ bubble(SHOPIN.cashier,'Dobar dan! Izvolite?',4); }catch(e){} UI.toast('🛒 U trgovini — priđi blagajni i pritisni E'); }
function exitShop(){ try{ blip('door'); }catch(e){} SHOPIN.inside=false; const b=SHOPIN.back||SHOP_POS(); teleport(b[0],b[1]); }
function shopSpot(){ if(!SHOPIN.inside) return null; const dx=PLAYER.pos.x-SHOPIN.x, dz=PLAYER.pos.z-SHOPIN.z; if(Math.hypot(dx-2.6,dz-2.9)<1.6) return 'till'; if(Math.hypot(dx,dz-4.6)<1.3) return 'door'; return null; }
/* ---- rideable bicycles ---- */
function makeRideBike(col){ const B=makeBike(col); const outer=new THREE.Group(); B.g.rotation.y=-Math.PI/2; outer.add(B.g); return {group:outer,wheels:[],wb:1.05,track:0.3,len:1.8,wid:0.55,r:0.34,bike:true,bk:B,label:'bicikl',col,halfL:0.9,phys:{maxV:9,rev:-2,acc:2.8,brake:7,maxSteer:0.55,sv:10}}; }
function spawnBikes(scene){ const spots=[[-395,6,8,3],[-224,-44,6,-4],[-267,-40,-4,5]]; for(const [x,z,dx,dz] of spots){ const p=offRoad(x+dx,z+dz,0.6); const v=makeRideBike([0x1f5fb0,0xc62828,0x2e8b3a][DRIVE.length%3]); placeVehicle(scene,v,p[0],p[1],Math.random()*TAU); } }
function bikeRiderTick(){ for(const v of DRIVE){ if(!v.bike) continue; v.bk.spin(v.st.spin||0); const o=carOccupants(v); if(!o.driver) continue; let A=null; const me=NET.myId||'me'; if(o.driver===me){ if(!ME_AV){ ME_AV=makeAvatar(NET.name||'Ti',NET.color||'#e8412c'); GAME.scene.add(ME_AV.group); } A=ME_AV; } else { const R=NET.remotes.get(o.driver); A=R&&R.av; } if(!A) continue;
    A.group.visible=!(o.driver===me&&CARCAM.first); A.seatT=GAME.time; A.bikeT=GAME.time; A.bikePh=(v.st.spin||0)*0.5; A.group.position.set(v.st.x,v.st.y+0.02,v.st.z); A.group.rotation.set(0,v.st.yaw,v.st.steer*-0.25); const ph=(v.st.spin||0)*0.5; A.legL.rotation.x=-0.75+Math.sin(ph)*0.42; A.legR.rotation.x=-0.75-Math.sin(ph)*0.42; A.armL.rotation.x=A.armR.rotation.x=-1.0; for(const bp of A.body) bp.visible=true; } }
/* ---- GTA-style banners, minimap blip + GPS line, wanted flash ---- */
function banner(big,small,col){ const el=document.getElementById('banner'); if(!el) return; el.querySelector('.b').textContent=big; el.querySelector('.s').textContent=small||''; el.style.setProperty('--bc',col||'#ffd24a'); el.classList.remove('on'); void el.offsetWidth; el.classList.add('on'); }
function miniOverlay(){ const c=document.getElementById('mini'); if(!c) return; const g=c.getContext('2d'); const S=c.width; const p=PLAYER.pos; const k=1.35; const yaw=PLAYER.driving?PLAYER.driving.st.yaw:PLAYER.yaw;
  const toMini=(x,z)=>{ const dx=(x-p.x)*MAP.scale*k, dz=(z-p.z)*MAP.scale*k; const c2=Math.cos(yaw), s2=Math.sin(yaw); return [S/2+dx*c2-dz*s2, S/2+dx*s2+dz*c2]; };
  g.save(); g.beginPath(); g.arc(S/2,S/2,S/2-2,0,TAU); g.clip();
  if(GTA.wanted>0){ const on=Math.floor(GAME.time*3)%2===0; g.fillStyle=on?'rgba(40,80,255,0.22)':'rgba(255,40,40,0.22)'; g.fillRect(0,0,S,S); }
  if(GTA.way){ const [bx,bz]=toMini(GTA.way[0],GTA.way[1]); const ang=Math.atan2(bz-S/2,bx-S/2); const r=Math.hypot(bx-S/2,bz-S/2); const R2=Math.min(r,S/2-9); const ex=S/2+Math.cos(ang)*R2, ez=S/2+Math.sin(ang)*R2; g.strokeStyle='#b44bff'; g.lineWidth=4; g.lineCap='round'; g.beginPath(); g.moveTo(S/2,S/2); g.lineTo(ex,ez); g.stroke(); g.fillStyle='#ffd24a'; g.strokeStyle='#161616'; g.lineWidth=2; g.beginPath(); g.arc(ex,ez,6,0,TAU); g.fill(); g.stroke(); }
  if(GTA.wanted>0&&COP.last&&COP.state!=='CHASE'){ const [x,y]=toMini(COP.last[0],COP.last[1]); const on=Math.floor(GAME.time*3)%2===0; g.strokeStyle=on?'rgba(60,110,255,0.9)':'rgba(255,60,60,0.9)'; g.fillStyle=on?'rgba(60,110,255,0.18)':'rgba(255,60,60,0.18)'; g.lineWidth=2; g.beginPath(); g.arc(x,y,Math.max(10,(55+GTA.wanted*12)*MAP.scale*k),0,TAU); g.fill(); g.stroke(); }
  for(const M of MISSIONS){ if(GTA.mission) break; if(typeof missionOpen==='function'&&!missionOpen(M)) continue; const q=npcPos(M.giver); if(!q) continue; let [x,y]=toMini(q[0],q[1]); const far=Math.hypot(x-S/2,y-S/2)>S/2-8; if(far&&!M.story) continue; if(far){ const a=Math.atan2(y-S/2,x-S/2); x=S/2+Math.cos(a)*(S/2-9); y=S/2+Math.sin(a)*(S/2-9); } g.fillStyle=M.story?'#ff8a2a':'#ffd24a'; g.strokeStyle='#161616'; g.lineWidth=1.5; g.beginPath(); g.arc(x,y,M.story?7:5,0,TAU); g.fill(); g.stroke(); g.fillStyle='#161616'; g.font='900 '+(M.story?10:8)+'px Arial'; g.textAlign='center'; g.textBaseline='alphabetic'; g.fillText(M.story?'★':'!',x,y+(M.story?3.5:3)); }
  for(const c of (typeof LAW!=='undefined'?LAW.crew:[])){ if(!c.out||c.A.dead) continue; const q=c.A.group.position; const [x,y]=toMini(q.x,q.z); if(Math.hypot(x-S/2,y-S/2)>S/2-4) continue; g.fillStyle=c.kind==='cop'?'#5a86ff':c.kind==='thug'?'#ff3b30':'#4fd06a'; g.beginPath(); g.arc(x,y,3,0,TAU); g.fill(); }
  { const ic=[[SHOP_POS(),'🛒'],...(typeof intIcons==='function'?intIcons():[]),[CAFE_POS(),'☕'],[LANDMARKS.fire?[LANDMARKS.fire.x,LANDMARKS.fire.z]:null,'🚒'],[LANDMARKS.churchDoor?[LANDMARKS.churchDoor.x,LANDMARKS.churchDoor.z]:null,'⛪'],[HOME_POS(),'🏠']]; for(const v of DRIVE) if(v.bike) ic.push([[v.st.x,v.st.z],'🚲']); g.font='11px sans-serif'; g.textAlign='center'; g.textBaseline='middle'; for(const [q,e] of ic){ if(!q) continue; const [x,y]=toMini(q[0],q[1]); if(Math.hypot(x-S/2,y-S/2)>S/2-8) continue; g.fillText(e,x,y); } }
  for(const C of GTA.chasers){ const [x,y]=toMini(C.st.x,C.st.z); g.fillStyle=C.kind==='policija'?'#3a6bff':'#e5483b'; g.beginPath(); g.arc(x,y,4,0,TAU); g.fill(); }
  g.restore(); }
function gta2Tick(dt){ peopleTick(dt); bikeRiderTick();
  if(SHOPIN.inside&&SHOPIN.cashier){ const A=SHOPIN.cashier; A.armR.rotation.x=-0.4+Math.sin(GAME.time*1.3)*0.2; } }

let POOL_MAT=null;
function bloodPool(A){ if(!POOL_MAT){ const c=cvs(128,128), g=c.getContext('2d'); const gr=g.createRadialGradient(64,64,4,64,64,62); gr.addColorStop(0,'rgba(70,4,4,0.95)'); gr.addColorStop(0.7,'rgba(90,6,6,0.85)'); gr.addColorStop(1,'rgba(90,6,6,0)'); g.fillStyle=gr; g.beginPath(); for(let k=0;k<=24;k++){ const a=k/24*TAU, r=48+Math.sin(k*2.7)*10; g.lineTo(64+Math.cos(a)*r,64+Math.sin(a)*r); } g.fill(); const t=new THREE.CanvasTexture(c); POOL_MAT=new THREE.MeshStandardMaterial({map:t,transparent:true,depthWrite:false,roughness:0.15,metalness:0.1,polygonOffset:true,polygonOffsetFactor:-4}); }
  const m=new THREE.Mesh(new THREE.PlaneGeometry(1.6,1.6),POOL_MAT); m.rotation.x=-Math.PI/2; m.scale.set(0.1,0.1,0.1); m.renderOrder=2; GAME.scene.add(m); A.pool=m; }

// running away: hit people (and everyone near a shooting) sprint away from you instead of standing there
function fleeFrom(A,from,t){ if(A.noCrime||A.dead) return; A.fleeT=Math.max(A.fleeT||0,t); A.fleeFrom=[from.x,from.z]; if(!A.fleePos) A.fleePos=A.group.position.clone(); }
function panicAround(p,r){ for(const P of allPeople()){ const A=P.A; if(A.dead||A.noCrime) continue; const q=A.group.position; if(Math.hypot(q.x-p.x,q.z-p.z)<r) fleeFrom(A,p,10+Math.random()*6); } }
function fleeStep(A,dt){ if(!A.fleePos) return false; if(A.fleeT>0){ A.fleeT-=dt; const p=A.fleePos; let dx=p.x-A.fleeFrom[0], dz=p.z-A.fleeFrom[1]; const d=Math.hypot(dx,dz)||1; dx/=d; dz/=d; const wob=Math.sin(GAME.time*1.7+p.x)*0.35; const ux=dx*Math.cos(wob)-dz*Math.sin(wob), uz=dx*Math.sin(wob)+dz*Math.cos(wob);
    let nx=p.x+ux*5.6*dt, nz=p.z+uz*5.6*dt; if(BHASH.hit(nx,nz,0.4)){ nx=p.x-uz*5.6*dt; nz=p.z+ux*5.6*dt; if(BHASH.hit(nx,nz,0.4)){ nx=p.x; nz=p.z; } } p.set(nx,groundAt(nx,nz),nz); A.group.rotation.y=faceYaw(ux,uz); A.spdOv=5.6; }
  else { A.spdOv=0; if(Math.hypot(A.fleePos.x-PLAYER.pos.x,A.fleePos.z-PLAYER.pos.z)>70||A.fleeT<-25){ A.fleePos=null; A.spdOv=undefined; A.fleeT=0; return false; } A.fleeT-=dt; }
  A.group.position.copy(A.fleePos); if(!A.real){ const ph=GAME.time*11; A.legL.rotation.x=Math.sin(ph)*0.8*(A.fleeT>0?1:0); A.legR.rotation.x=-Math.sin(ph)*0.8*(A.fleeT>0?1:0); A.armL.rotation.x=A.armR.rotation.x=A.fleeT>0?-1.2:0; } return true; }
