/* ===================== TUHELJ OPEN WORLD: HUD, inventar, mobitel, spremanje, dan/noć, kiša, zvuk, policija AI ===================== */
const OW={stam:100,inv:{},msgs:[],phone:false,app:'home',rain:0,rainT:120,saveT:0,dbg:false,fps:60,lastY:0,fallV:0,panic:0,clockT:0};
const ITEMS={hrana:{n:'Sendvič',ic:'🥪',hp:35},voda:{n:'Voda',ic:'💧',hp:10},sok:{n:'Sok',ic:'🧃',hp:15},lijek:{n:'Lijekovi',ic:'💊',hp:100},alat:{n:'Alat',ic:'🔧'},mobitel:{n:'Mobitel',ic:'📱'},kljuc:{n:'Ključevi',ic:'🔑'}};
/* ---- save / load ---- */
function owSave(){ try{ const s={v:1,skin:OW.skin||0,skinSet:!!OW.skinSet,money:GTA.money,inv:OW.inv,done:GTA.done,home:GTA.home,hour:GAME.hour,pos:(typeof INSIDE!=='undefined'&&INSIDE&&INSIDE.back)?[+INSIDE.back[0].toFixed(1),+INSIDE.back[1].toFixed(1)]:[+PLAYER.pos.x.toFixed(1),+PLAYER.pos.z.toFixed(1)],msgs:OW.msgs.slice(-12),hp:Math.round(COMBAT.hp)}; localStorage.setItem('tuhelj_save',JSON.stringify(s)); }catch(e){} }
function owLoad(){ try{ const s=JSON.parse(localStorage.getItem('tuhelj_save')||'null'); if(!s) { OW.inv={mobitel:1,kljuc:1}; return; } if(Number.isFinite(s.money)) GTA.money=s.money; OW.skin=(Number.isInteger(s.skin)&&s.skin>=0&&s.skin<(typeof SKINS!=='undefined'?SKINS.length:2))?s.skin:0; OW.skinSet=!!s.skinSet; OW.inv=s.inv&&typeof s.inv==='object'?s.inv:{mobitel:1,kljuc:1}; if(s.done) GTA.done=s.done; GTA.home=!!s.home; if(Number.isFinite(s.hour)) GAME.hour=s.hour; OW.msgs=Array.isArray(s.msgs)?s.msgs:[]; OW.loadPos=Array.isArray(s.pos)?s.pos:null; if(Number.isFinite(s.hp)) COMBAT.hp=Math.max(30,s.hp); }catch(e){ OW.inv={mobitel:1,kljuc:1}; } }
/* ---- inventory ---- */
function invAdd(k,n){ OW.inv[k]=(OW.inv[k]||0)+(n||1); owSave(); }
function invUse(k){ const it=ITEMS[k]; if(!it||!OW.inv[k]) return; if(it.hp){ if(COMBAT.hp>=100){ UI.toast('Zdravlje je već puno'); return; } COMBAT.hp=Math.min(100,COMBAT.hp+it.hp); OW.inv[k]--; UI.toast(it.ic+' '+it.n+' (+'+it.hp+' ❤)'); updateCombatHUD(); }
  else if(k==='alat'){ const v=nearestVehicle(PLAYER.pos.x,PLAYER.pos.z,4,true)||PLAYER.driving; if(!v){ UI.toast('Priđi vozilu da ga popraviš'); return; } v.hp=100; v.dead=false; OW.inv[k]--; UI.toast('🔧 Vozilo popravljeno'); }
  else { UI.toast(it.ic+' '+it.n); return; } if(OW.inv[k]<=0) delete OW.inv[k]; owSave(); renderPhone(); }
/* shop now fills the inventory (pay at the till, get the item) */
const SHOP2=[{k:'hrana',p:3},{k:'voda',p:1},{k:'sok',p:2},{k:'lijek',p:12},{k:'alat',p:15}];
function openShop(){ const el=document.getElementById('shopmenu'); if(!el) return; const list=document.getElementById('shoplist'); list.replaceChildren(...SHOP2.map(it=>{ const I=ITEMS[it.k]; const b=document.createElement('button'); b.className='drink'; const n=document.createElement('span'); n.textContent=I.ic+'  '+I.n+(I.hp?'  (+'+I.hp+' ❤)':it.k==='alat'?'  (popravak vozila)':''); const p=document.createElement('b'); p.textContent=it.p+' €'; b.append(n,p); b.addEventListener('click',()=>{ if(GTA.money<it.p){ UI.toast('Nemaš dovoljno novca'); return; } money(-it.p); invAdd(it.k); UI.toast('Kupljeno: '+I.ic+' '+I.n+' → u inventaru'); try{ bubble(SHOPIN.cashier,'Hvala, doviđenja!',2.5); }catch(e){} }); return b; })); el.classList.add('on'); COMBAT.menuOpen=true; PLAYER.enabled=false; if(document.pointerLockElement) document.exitPointerLock(); }
/* ---- phone ---- */
function sendMsg(from,text,mid){ OW.msgs.push({from,text,mid:mid||null,t:Math.round(GAME.hour*100)/100,read:false}); owSave(); const b=document.getElementById('phonebadge'); if(b) b.style.display='block'; UI.toast('📱 Nova poruka: '+from); renderPhone(); }
function togglePhone(on){ OW.phone=on===undefined?!OW.phone:on; OW.app='home'; const el=document.getElementById('phone'); el.classList.toggle('on',OW.phone); if(OW.phone){ if(document.pointerLockElement) document.exitPointerLock(); COMBAT.menuOpen=true; PLAYER.enabled=false; } else { COMBAT.menuOpen=false; PLAYER.enabled=true; if(!GAME.touch&&!GAME.dragLook){ try{ GAME.renderer.domElement.requestPointerLock(); }catch(e){} } } renderPhone(); }
function renderPhone(){ const el=document.getElementById('phonebody'); if(!el||!OW.phone) return; const h=Math.floor(GAME.hour), m=Math.floor((GAME.hour-h)*60); document.getElementById('phoneclock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'); el.replaceChildren();
  const row=(ic,txt,fn,badge)=>{ const b=document.createElement('button'); b.className='papp'; const i=document.createElement('span'); i.className='pi'; i.textContent=ic; const t=document.createElement('span'); t.textContent=txt; b.append(i,t); if(badge){ const d=document.createElement('i'); d.className='pb'; d.textContent=badge; b.append(d); } b.addEventListener('click',fn); el.append(b); return b; };
  const back=()=>row('◀','Natrag',()=>{ OW.app='home'; renderPhone(); });
  if(OW.app==='home'){ const unread=OW.msgs.filter(q=>!q.read).length; row('👤','Kontakti',()=>{ OW.app='contacts'; renderPhone(); }); row('💬','Poruke',()=>{ OW.app='msgs'; renderPhone(); },unread||0); row('🗺️','Mapa',()=>{ togglePhone(false); try{ openMap(true); }catch(e){ UI.toast('Karta: tipka M'); } }); row('🎯','Misije',()=>{ OW.app='missions'; renderPhone(); }); row('🎒','Inventar',()=>{ OW.app='inv'; renderPhone(); }); row('⚙️','Postavke',()=>{ OW.app='set'; renderPhone(); }); return; }
  back();
  if(OW.app==='msgs'){ if(!OW.msgs.length){ const p=document.createElement('p'); p.textContent='Nema poruka.'; el.append(p); } for(const q of OW.msgs.slice().reverse()){ q.read=true; const box=document.createElement('div'); box.className='pmsg'; const a=document.createElement('b'); a.textContent=q.from; const t=document.createElement('div'); t.textContent=q.text; box.append(a,t);
      if(q.mid&&!GTA.mission){ const M=MISSIONS.find(x=>x.id===q.mid); if(M){ const ac=document.createElement('button'); ac.className='pbtn ok'; ac.textContent='PRIHVATI'; ac.onclick=()=>{ q.mid=null; togglePhone(false); startMission(M); }; const dc=document.createElement('button'); dc.className='pbtn no'; dc.textContent='ODBIJ'; dc.onclick=()=>{ q.mid=null; q.text+=' (odbijeno)'; renderPhone(); }; box.append(ac,dc); } } el.append(box); } const bdg=document.getElementById('phonebadge'); if(bdg) bdg.style.display='none'; owSave(); }
  if(OW.app==='contacts'){ for(const M of MISSIONS){ row('📞',M.giver,()=>{ if(GTA.mission){ UI.toast(M.giver+': Javi se kad završiš ovo što radiš!'); return; } sendMsg(M.giver,'Ej, možeš mi pomoći? — '+M.title,M.id); OW.app='msgs'; renderPhone(); }); } }
  if(OW.app==='missions'){ for(const M of MISSIONS){ const d=GTA.done[M.id]; row(d?'✅':'🎯',M.title+(d?' ('+d+'×)':'')+' · '+M.reward+' €',()=>{ const p=npcPos(M.giver); if(p){ setWay(p); togglePhone(false); UI.toast('📍 Označeno: '+M.giver); } }); } }
  if(OW.app==='inv'){ const ks=Object.keys(OW.inv); if(!ks.length){ const p=document.createElement('p'); p.textContent='Inventar je prazan.'; el.append(p); } for(const k of ks){ const I=ITEMS[k]; if(!I) continue; row(I.ic,I.n+' × '+OW.inv[k]+(I.hp||k==='alat'?'  — upotrijebi':''),()=>invUse(k)); } const c=document.createElement('p'); c.textContent='Novac: € '+GTA.money; el.append(c); }
  if(OW.app==='set'){ row(OW.muted?'🔇':'🔊','Zvuk: '+(OW.muted?'isključen':'uključen'),()=>{ OW.muted=!OW.muted; if(AUD.master) AUD.master.gain.value=OW.muted?0:0.6; renderPhone(); }); row('🌧️','Vrijeme: '+(OW.rain>0.5?'kiša':'sunčano'),()=>{ OW.rainTarget=OW.rain>0.5?0:1; OW.rainT=240; renderPhone(); }); row('🕒','Sat: '+Math.floor(GAME.hour)+'h (+3h)',()=>{ GAME.hour=(GAME.hour+3)%24; setTimeOfDay(GAME.renderer,GAME.scene,GAME.hour); nightLights(); renderPhone(); }); row('🧍','Izgled lika: '+((SKINS[OW.skin|0]||SKINS[0]).n),()=>{ OW.skin=((OW.skin|0)+1)%SKINS.length; OW.skinSet=true; owSave(); UI.toast(OW.skin?'Prijatelji te sad vide kao: '+SKINS[OW.skin].n:'Obični izgled'); renderPhone(); }); row('👥','Realistični mještani: '+(OW.realPeople===false?'isključeni':'uključeni'),()=>{ OW.realPeople=OW.realPeople===false; UI.toast(OW.realPeople===false?'Mještani su opet jednostavni (brže na slabijim mobitelima)':'Mještani su realistični'); renderPhone(); }); row('💾','Spremi igru',()=>{ owSave(); UI.toast('💾 Spremljeno'); }); } }
/* ---- day / night ---- */
function nightLights(){ const n=SKY.night||0; const bm=GAME.bm||{}; for(const k of ['win','glassW']){ const m=bm[k]; if(m&&m.emissive){ if(!m.userData.nl){ m.userData.nl=true; m.emissive=new THREE.Color(0xffc27a); m.emissiveMap=m.map||null; } m.emissiveIntensity=n*0.55; } } const g=bm.glow; if(g&&g.emissive!==undefined){ if(!g.userData.base) g.userData.base=g.emissiveIntensity||1; g.emissiveIntensity=g.userData.base*(1+n*1.6); } }
function clockTick(dt){ GAME.hour=((GAME.hour||10)+dt/60*0.5)%24; OW.clockT+=dt; if(OW.clockT>8){ OW.clockT=0; setTimeOfDay(GAME.renderer,GAME.scene,GAME.hour); nightLights(); } }
/* ---- rain ---- */
function rainTick(dt){ OW.rainT-=dt; if(OW.rainT<=0){ OW.rainT=150+Math.random()*200; OW.rainTarget=Math.random()<0.3?1:0; } const tgt=OW.rainTarget||0; OW.rain+=(tgt-OW.rain)*Math.min(1,dt*0.2);
  if(!OW.drops){ const N=1400; const geo=new THREE.BufferGeometry(); const pos=new Float32Array(N*6); for(let i=0;i<N;i++){ const x=(Math.random()-0.5)*50, y=Math.random()*25, z=(Math.random()-0.5)*50; pos.set([x,y,z,x+0.05,y-0.55,z],i*6); } geo.setAttribute('position',new THREE.BufferAttribute(pos,3)); OW.drops=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0xaec2d6,transparent:true,opacity:0.5})); OW.drops.frustumCulled=false; GAME.scene.add(OW.drops); OW.baseFog=GAME.scene.fog.density||null; }
  const d=OW.drops; d.visible=OW.rain>0.05; if(d.visible){ const c=GAME.camera.position; d.position.set(c.x,c.y-8+((GAME.time*22)%25)*-1+12,c.z); d.material.opacity=0.45*OW.rain; }
  if(SKY.sun) SKY.sun.intensity*=1; GAME.scene.fog&&GAME.scene.fog.density!==undefined&&OW.baseFog!==null&&(GAME.scene.fog.density=OW.baseFog*(1+OW.rain*2.2)); if(SKY.hemi) SKY.hemi.intensity=Math.max(0.12,SKY.hemi.intensity); if(AUD.rain) AUD.rain.gain.value=OW.rain*0.22; }
/* ---- audio (synthesized, event-driven) ---- */
const AUD={};
function audInit(){ if(AUD.ctx) return; try{ const C=new (window.AudioContext||window.webkitAudioContext)(); AUD.ctx=C; AUD.master=C.createGain(); AUD.master.gain.value=0.6; AUD.master.connect(C.destination);
  const nb=C.createBuffer(1,C.sampleRate*2,C.sampleRate), dd=nb.getChannelData(0); for(let i=0;i<dd.length;i++) dd[i]=Math.random()*2-1; AUD.noise=nb;
  const eng=C.createOscillator(); eng.type='sawtooth'; const ef=C.createBiquadFilter(); ef.type='lowpass'; ef.frequency.value=420; const eg=C.createGain(); eg.gain.value=0; eng.connect(ef); ef.connect(eg); eg.connect(AUD.master); eng.start(); AUD.eng=eng; AUD.engG=eg;
  const sir=C.createOscillator(); sir.type='square'; const sg=C.createGain(); sg.gain.value=0; const sf=C.createBiquadFilter(); sf.type='lowpass'; sf.frequency.value=1800; sir.connect(sf); sf.connect(sg); sg.connect(AUD.master); sir.start(); AUD.sir=sir; AUD.sirG=sg;
  const rn=C.createBufferSource(); rn.buffer=nb; rn.loop=true; const rf=C.createBiquadFilter(); rf.type='highpass'; rf.frequency.value=900; const rg=C.createGain(); rg.gain.value=0; rn.connect(rf); rf.connect(rg); rg.connect(AUD.master); rn.start(); AUD.rain=rg; }catch(e){} }
function blip(type){ const C=AUD.ctx; if(!C||OW.muted) return; const t=C.currentTime; const g=C.createGain(); g.connect(AUD.master);
  if(type==='shot'||type==='boom'||type==='step'||type==='door'){ const s=C.createBufferSource(); s.buffer=AUD.noise; const f=C.createBiquadFilter(); f.type=type==='boom'?'lowpass':'bandpass'; f.frequency.value=type==='boom'?300:type==='step'?500:type==='door'?250:1400; s.connect(f); f.connect(g); const v=type==='boom'?0.9:type==='shot'?0.55:type==='door'?0.3:0.07; const d=type==='boom'?1.2:type==='shot'?0.18:type==='door'?0.25:0.06; g.gain.setValueAtTime(v,t); g.gain.exponentialRampToValueAtTime(0.001,t+d); s.start(t,Math.random()); s.stop(t+d+0.05); }
  else if(type==='bird'){ const o=C.createOscillator(); o.type='sine'; const f0=2400+Math.random()*1600; o.frequency.setValueAtTime(f0,t); o.frequency.exponentialRampToValueAtTime(f0*1.4,t+0.08); o.frequency.exponentialRampToValueAtTime(f0*0.9,t+0.16); o.connect(g); g.gain.setValueAtTime(0.0001,t); g.gain.exponentialRampToValueAtTime(0.05,t+0.02); g.gain.exponentialRampToValueAtTime(0.0001,t+0.18); o.start(t); o.stop(t+0.2); }
  else if(type==='coin'){ const o=C.createOscillator(); o.type='triangle'; o.frequency.setValueAtTime(880,t); o.frequency.setValueAtTime(1320,t+0.08); o.connect(g); g.gain.setValueAtTime(0.18,t); g.gain.exponentialRampToValueAtTime(0.001,t+0.3); o.start(t); o.stop(t+0.32); } }
function audioTick(dt){ if(!AUD.ctx){ if(GAME.started) audInit(); return; } if(AUD.ctx.state==='suspended') AUD.ctx.resume().catch(()=>{}); const v=PLAYER.driving; const sp=v?Math.abs(v.st.v):0;
  AUD.engG.gain.value=OW.muted?0:(v&&!v.bike?0.05+Math.min(0.08,sp*0.004):PLAYER.heli?0.1:0); AUD.eng.frequency.value=v?(v.formula?90+sp*9:45+sp*4.5):PLAYER.heli?38:40;
  let pd=1e9; for(const C of GTA.chasers) if(C.kind==='policija'||C.kind==='hitna') pd=Math.min(pd,Math.hypot(C.st.x-PLAYER.pos.x,C.st.z-PLAYER.pos.z)); for(const C of GTA.amb) pd=Math.min(pd,Math.hypot(C.st.x-PLAYER.pos.x,C.st.z-PLAYER.pos.z));
  AUD.sirG.gain.value=OW.muted?0:(pd<160?0.05*(1-pd/160):0); AUD.sir.frequency.value=(Math.floor(GAME.time*1.6)%2)?960:720;
  OW.stepT=(OW.stepT||0)+dt; const moving=!v&&!PLAYER.heli&&PLAYER.ground&&Math.hypot(PLAYER.vel.x,PLAYER.vel.z)>1; if(moving&&OW.stepT>(KEYS.ShiftLeft||TOUCH.run?0.28:0.45)){ OW.stepT=0; blip('step'); }
  if((SKY.night||0)<0.4&&OW.rain<0.3&&Math.random()<dt*0.35) blip('bird'); }
/* ---- stamina + fall damage ---- */
function staminaTick(dt){ const running=(KEYS.ShiftLeft||KEYS.ShiftRight||TOUCH.run)&&!PLAYER.driving&&Math.hypot(PLAYER.vel.x,PLAYER.vel.z)>3; OW.stam=Math.max(0,Math.min(100,OW.stam+(running?-14:9)*dt)); if(OW.stam<=0.5){ KEYS.ShiftLeft=false; KEYS.ShiftRight=false; if(TOUCH.run){ TOUCH.run=false; const rb=document.getElementById('runbtn'); if(rb) rb.classList.remove('on'); } }
  if(!PLAYER.driving&&!PLAYER.heli&&!PLAYER.fly){ const vy=PLAYER.vel.y; if(!PLAYER.ground) OW.fallV=Math.min(OW.fallV,vy); else { if(OW.fallV<-13){ takeDamage(Math.round((-OW.fallV-13)*9),'pad'); UI.toast('Au! Pao si s visine'); } OW.fallV=0; } } }
/* ---- vehicle health & damage ---- */
function vehicleDamageTick(dt){ for(const v of DRIVE){ if(v.hp===undefined) v.hp=100; const s=v.st; const sp=Math.abs(s.v||0); if(v._pv!==undefined){ const dv=v._pv-sp; if(dv>7&&!v.bike){ v.hp=Math.max(0,v.hp-dv*3.2); if(v===PLAYER.driving){ COMBAT.shake=Math.max(COMBAT.shake,Math.min(0.6,dv*0.04)); blip('door'); } if(v.hp<=0&&!v.dead){ v.dead=true; if(v===PLAYER.driving) UI.toast('💥 Vozilo je uništeno — treba ti 🔧 alat iz trgovine'); } } } v._pv=sp;
    if(v.dead&&v===PLAYER.driving){ s.v*=Math.exp(-dt*2); } if(v.hp<45&&Math.random()<dt*(v.dead?8:2.5)){ const p=new THREE.Vector3((v.halfL||2)*0.7,1.1,0); v.group.localToWorld(p); puff(p,0.8,v.dead?0x2a2a2a:0x8a8a8a); } } }
/* ---- pedestrians react: flee from shots / deaths / police ---- */
function panicTick(dt){ if(OW.panic>0) OW.panic-=dt; for(const Q of GTA.peds){ const A=Q.A; if(A.dead) continue; if(OW.panic>0){ const dx=A.group.position.x-PLAYER.pos.x, dz=A.group.position.z-PLAYER.pos.z, d=Math.hypot(dx,dz)||1; if(d<45){ const nx=A.group.position.x+dx/d*4.2*dt, nz=A.group.position.z+dz/d*4.2*dt; if(!BHASH.hit(nx,nz,0.3)){ A.group.position.x=nx; A.group.position.z=nz; A.group.position.y=groundAt(nx,nz); } A.group.rotation.y=faceYaw(dx,dz); const ph=GAME.time*11; A.legL.rotation.x=Math.sin(ph)*0.8; A.legR.rotation.x=-Math.sin(ph)*0.8; A.armL.rotation.x=A.armR.rotation.x=-1.2; Q.fled=true; } } else if(Q.fled){ Q.fled=false; } } }
/* ---- police state machine: PATROL → ALERT → INVESTIGATE → CHASE → SEARCH → RETURN ---- */
const COP={state:'PATROL',last:null,seenT:0,searchT:0,alertT:0};
function copSees(C){ const dx=PLAYER.pos.x-C.st.x, dz=PLAYER.pos.z-C.st.z, d=Math.hypot(dx,dz); if(d>75) return false; for(let t=0.1;t<1;t+=0.1){ const x=C.st.x+dx*t, z=C.st.z+dz*t; const hb=BHASH.hit(x,z,0); if(hb&&hb.hl>1.5&&hb.hw>1.5) return false; } return true; }
function crimeEvent(x,z,stars){ GTA.wanted=Math.min(5,Math.max(GTA.wanted,0)+stars); GTA.wantT=0; COP.last=[x,z]; COP.state=COP.state==='CHASE'?'CHASE':'ALERT'; COP.alertT=0; OW.panic=12; }
function policeTick(dt){ const cops=GTA.chasers.filter(c=>c.kind==='policija'&&!c.wreck&&!(c.burnT>0)); const want=GTA.wanted;
  if(want>0){ const need=Math.min(4,want); while(cops.length<need){ const C=makeAI('policija'); const a=Math.random()*TAU; let x=(COP.last||[PLAYER.pos.x,PLAYER.pos.z])[0]+Math.cos(a)*170, z=(COP.last||[PLAYER.pos.x,PLAYER.pos.z])[1]+Math.sin(a)*170; const n=nearestRoad(x,z,90); if(n){ x=n.s.x; z=n.s.z; } C.st.x=x; C.st.z=z; C.st.yaw=0; GTA.chasers.push(C); cops.push(C); } }
  const seen=cops.some(copSees); if(seen){ COP.last=[PLAYER.pos.x,PLAYER.pos.z]; COP.seenT=0; if(want>0) COP.state='CHASE'; } else COP.seenT+=dt;
  if(want>0){ if(COP.state==='ALERT'){ COP.alertT+=dt; if(COP.alertT>1.5) COP.state='INVESTIGATE'; } if(COP.state==='CHASE'&&!seen&&COP.seenT>3) { COP.state='SEARCH'; COP.searchT=0; } if(COP.state==='SEARCH'){ COP.searchT+=dt; if(COP.searchT>13){ GTA.wanted=Math.max(0,GTA.wanted-1); COP.searchT=0; if(!GTA.wanted) COP.state='RETURN'; } } }
  else if(cops.length) COP.state='RETURN'; else COP.state='PATROL';
  GTA.wantT=0; for(const C of cops){ if(COP.state==='RETURN'){ C.leave=true; continue; } C.leave=false; const tgt=COP.state==='CHASE'?[PLAYER.pos.x,PLAYER.pos.z]:(COP.last||[PLAYER.pos.x,PLAYER.pos.z]); C.tgt=tgt; C.wander=COP.state==='SEARCH'; }
  const w=document.getElementById('copstate'); if(w){ const L={ALERT:'UZBUNA',INVESTIGATE:'ISTRAGA',CHASE:'POTJERA',SEARCH:'TRAŽE TE',RETURN:'',PATROL:''}[COP.state]; w.textContent=want>0?L:''; } }
/* ---- debug overlay (F3) ---- */
function dbgTick(dt){ OW.fps=OW.fps*0.95+(1/Math.max(0.001,dt))*0.05; const el=document.getElementById('dbg'); if(!el) return; el.style.display=OW.dbg?'block':'none'; if(!OW.dbg) return; const info=GAME.renderer.info; el.textContent='FPS '+OW.fps.toFixed(0)+' | NPC '+allPeople().length+' | vozila '+(DRIVE.length+GTA.traffic.length+GTA.chasers.length+GTA.amb.length)+'\nX '+PLAYER.pos.x.toFixed(1)+' Y '+PLAYER.pos.y.toFixed(1)+' Z '+PLAYER.pos.z.toFixed(1)+' | sat '+GAME.hour.toFixed(1)+'\nwanted '+GTA.wanted+' ('+COP.state+') | misija '+(GTA.mission?GTA.mission.id+' #'+GTA.step:'-')+'\nHP '+Math.round(COMBAT.hp)+' | stamina '+Math.round(OW.stam)+' | draw '+info.render.calls+' | tri '+(info.render.triangles/1000).toFixed(0)+'k'; }
/* ---- HUD ---- */
function hudTick(){ const hf=document.getElementById('hphud'), sf=document.getElementById('sthud'), hv=document.getElementById('hpval'), cash=document.getElementById('cashval'), wst=document.getElementById('wstars'); if(hf) hf.style.width=Math.max(0,COMBAT.hp)+'%'; if(hv) hv.textContent=Math.round(COMBAT.hp); if(sf) sf.style.width=OW.stam+'%'; if(cash) cash.textContent='€'+GTA.money; if(wst){ const s='★'.repeat(GTA.wanted)+'☆'.repeat(5-GTA.wanted); if(wst.textContent!==s) wst.textContent=s; document.getElementById('wbox').classList.toggle('hot',GTA.wanted>0); }
  const ob=document.getElementById('objcard'); if(ob){ const M=GTA.mission; ob.style.display=M?'flex':'none'; if(M){ const S=M.steps[GTA.step]; const t=ob.querySelector('.t'), d=ob.querySelector('.d'); if(t.textContent!==M.title) t.textContent=M.title; const od=document.querySelector('#objective div'); const tx=od?od.textContent.replace('CILJ: ',''):S.t; if(d.textContent!==tx) d.textContent=tx; } } }
/* ---- extra missions: bike newspapers, shop errand, police escape ---- */
MISSIONS.push(
 {id:'novine',giver:'Tuljulju',title:'Novine biciklom',reward:120,intro:[['Tuljulju','Poštar je bolestan, a ljudi čekaju novine!'],['Tuljulju','Uzmi bicikl i obiđi tri kuće po selu.']],steps:[{t:'Sjedni na bicikl',ok:()=>PLAYER.driving&&PLAYER.driving.bike,onStart:()=>{ const b=DRIVE.find(v=>v.bike); GTA.cps=b?roadPath(b.st.x,b.st.z,420,0.55).filter((p,i)=>i%30===29).slice(0,3):[]; }},{t:'Dostavi novine',race:true,bike:true,time:240}],outro:[['Tuljulju','Svi su dobili novine. Evo ti 120 eura!']]},
 {id:'nabava',giver:'Lidija',title:'Nabava za kafić',reward:90,intro:[['Lidija','Nestalo nam je soka za djecu na terasi.'],['Lidija','Kupi dva soka u trgovini i donesi mi ih za šank.']],steps:[{t:'Kupi 2 soka u trgovini',ok:()=>(OW.inv.sok||0)>=2},{t:'Donesi sokove Lidiji',at:()=>npcPos('Lidija'),r:3.2,onDone:()=>{ OW.inv.sok-=2; if(OW.inv.sok<=0) delete OW.inv.sok; money(4,'Lidija ti vratila za sokove'); }}],outro:[['Lidija','Hvala ti, spasio si terasu!']]},
 {id:'bijeg',giver:'Vatrogasac Krtek',title:'Bijeg od policije',reward:250,intro:[['Vatrogasac Krtek','Policija misli da si ti krivac za požar!'],['Vatrogasac Krtek','Pobjegni im i izgubi sve zvjezdice — onda ćemo raščistiti.']],steps:[{t:'Izgubi policiju (0 zvjezdica)',ok:()=>GTA.wanted===0&&GTA.stepT>3,onStart:()=>crimeEvent(PLAYER.pos.x,PLAYER.pos.z,2),time:240}],outro:[['Vatrogasac Krtek','Uf! Sve je raščišćeno. Evo 250 eura.']]});
/* phone offers now and then */
function offersTick(dt){ OW.offerT=(OW.offerT||40)-dt; if(OW.offerT<=0){ OW.offerT=110+Math.random()*90; if(GTA.mission) return; const avail=MISSIONS.filter(M=>!GTA.done[M.id]); const M=(avail.length?avail:MISSIONS)[Math.floor(Math.random()*(avail.length||MISSIONS.length))]; sendMsg(M.giver,'Ej, možeš mi pomoći? — '+M.title,M.id); } }
/* ---- per-frame + input ---- */
function owTick(dt){ if(!OW.init){ OW.init=true; if(OW.loadPos&&GAME.started){ const p=OW.loadPos; if(Math.hypot(p[0],p[1])<3000) teleport(p[0],p[1]); } money(0); }
  try{ clockTick(dt); rainTick(dt); staminaTick(dt); vehicleDamageTick(dt); panicTick(dt); policeTick(dt); offersTick(dt); audioTick(dt); hudTick(); dbgTick(dt); }catch(e){ console.warn('ow',e); }
  OW.saveT+=dt; if(OW.saveT>10){ OW.saveT=0; owSave(); } }
addEventListener('keydown',e=>{ if(e.target&&e.target.tagName==='INPUT') return; if(e.code==='KeyP'&&GAME.started){ togglePhone(); } if(e.code==='F3'){ e.preventDefault(); OW.dbg=!OW.dbg; } if(e.code==='KeyI'&&GAME.started){ if(!OW.phone) togglePhone(true); OW.app='inv'; renderPhone(); } });
addEventListener('beforeunload',()=>owSave()); owLoad();

function crime(n){ crimeEvent(PLAYER.pos.x,PLAYER.pos.z,n); }
