/* ===================== your home: stan Kod Ruže =====================
   Wardrobe (outfits, previewed on your character), bed (sleep until morning/evening, saves the game),
   shower (sober up), TV (local news that follow the story) and "Uredi stan" — buy furniture that stays in the flat. */
const HOME={spots:null,decor:new Set(),built:{},menu:null,showcase:false};
try{ const d=JSON.parse(localStorage.getItem('tuhelj_decor')||'[]'); if(Array.isArray(d)) for(const k of d) HOME.decor.add(k); }catch(e){}
/* ---- generic menu sheet (used by the wardrobe, decor shop, story) ---- */
function gMenu(title,sub,items,opt){ opt=opt||{}; let el=document.getElementById('gmenu'); if(!el){ el=document.createElement('div'); el.id='gmenu'; el.innerHTML='<div class="dm"><h3></h3><p></p><div class="gl"></div><button class="btn gx">Zatvori</button></div>'; document.body.appendChild(el);
    const st=document.createElement('style'); st.textContent='#gmenu{position:fixed;inset:0;display:none;align-items:center;justify-content:flex-end;padding:0 4vw;background:linear-gradient(90deg,rgba(10,12,10,0) 30%,rgba(10,12,10,.55));z-index:40}#gmenu.on{display:flex}#gmenu.mid{justify-content:center;background:rgba(10,12,10,.55)}#gmenu .dm{background:var(--panel-strong);border:1px solid var(--line);border-radius:18px;padding:18px 18px 14px;width:min(400px,92vw);max-height:86vh;overflow:auto}#gmenu h3{font-family:var(--serif);font-size:32px;font-weight:400;margin:0 0 2px}#gmenu p{margin:0 0 12px;color:var(--muted);font-size:13px;line-height:1.45}#gmenu .gl{display:flex;flex-direction:column;gap:6px;margin-bottom:12px}#gmenu .drink{cursor:pointer;text-align:left}#gmenu .drink.sel{border-color:var(--accent);background:rgba(216,101,58,.22)}#gmenu .drink[disabled]{opacity:.45;cursor:default}#gmenu .drink small{display:block;font-weight:500;color:var(--muted);font-size:12px;margin-top:2px}';
    document.head.appendChild(st); el.querySelector('.gx').addEventListener('click',()=>gMenuClose()); }
  el.classList.toggle('mid',!opt.side); el.querySelector('h3').textContent=title; el.querySelector('p').textContent=sub||'';
  const list=el.querySelector('.gl'); list.replaceChildren(...items.map(it=>{ const b=document.createElement('button'); b.className='drink'+(it.sel?' sel':''); if(it.disabled) b.disabled=true; const n=document.createElement('span'); n.textContent=it.label; if(it.sub){ const s=document.createElement('small'); s.textContent=it.sub; n.append(s); } const r=document.createElement('b'); r.textContent=it.right||''; b.append(n,r); b.addEventListener('click',()=>{ if(!it.disabled) it.fn(); }); return b; }));
  el.classList.add('on'); HOME.menu={onClose:opt.onClose}; COMBAT.menuOpen=true; PLAYER.enabled=false; if(document.pointerLockElement) document.exitPointerLock(); }
function gMenuClose(){ const el=document.getElementById('gmenu'); if(el) el.classList.remove('on'); const m=HOME.menu; HOME.menu=null; COMBAT.menuOpen=false; PLAYER.enabled=true; HOME.showcase=false; if(m&&m.onClose) m.onClose(); if(!GAME.touch&&!GAME.dragLook){ try{ GAME.renderer.domElement.requestPointerLock(); }catch(e){} } }
addEventListener('keydown',e=>{ if(e.code==='Escape'&&HOME.menu) gMenuClose(); });
/* ---- spots inside the flat (local coordinates of 06e_apartment) ---- */
function homeLocal(x,z){ const A=LANDMARKS.aptF; if(!A) return null; const p=A.F(x,0,z); return [p[0],p[2]]; }
function homeSpots(){ if(HOME.spots||!LANDMARKS.aptF) return HOME.spots; HOME.spots=[
    {x:-1.05,z:-2.35,r:0.95,t:'👕 Ormar — presvuci se',fn:openWardrobe},
    {x:0.6,z:-1.7,r:1.1,t:'🛏️ Krevet — odspavaj (spremi igru)',fn:sleepMenu},
    {x:-2.45,z:-2.4,r:0.9,t:'🚿 Tuš — istuširaj se',fn:shower},
    {x:0.9,z:0.45,r:1.1,t:'📺 Televizor — Zagorje TV vijesti',fn:watchTV},
    {x:-1.2,z:2.55,r:1.0,t:'🛋️ Uredi stan — namještaj',fn:decorMenu}]; return HOME.spots; }
function inHome(){ const A=LANDMARKS.aptF; if(!A||INSIDE) return false; const dx=PLAYER.pos.x-A.F(0,0,0)[0], dz=PLAYER.pos.z-A.F(0,0,0)[2]; const c=Math.cos(A.ang), s=Math.sin(A.ang); const lx=dx*c+dz*s, lz=-dx*s+dz*c; return lx>-5.9&&lx<2.1&&lz>-3.1&&lz<3.1&&PLAYER.pos.y>getHeight(PLAYER.pos.x,PLAYER.pos.z)-0.5; }
function homeSpot(){ if(!inHome()||PLAYER.driving) return null; const S=homeSpots(); if(!S) return null; for(const s of S){ const p=homeLocal(s.x,s.z); if(Math.hypot(PLAYER.pos.x-p[0],PLAYER.pos.z-p[1])<s.r) return s; } return null; }
{ const _p=intPrompt, _u=intUse;
  intPrompt=function(){ const h=homeSpot(); if(h) return GTA.home?h.t:'🔒 Ovo je stan Kod Ruže — još nije tvoj'; return _p(); };
  intUse=function(){ const h=homeSpot(); if(h){ if(GTA.home) h.fn(); else UI.toast('Stan još nije tvoj — nastavi priču ili ga kupi (800 €) na ulazu'); return true; } return _u(); }; }
/* ---- wardrobe ---- */
const OUTFIT_LOCK={7:{need:()=>STORY&&STORY.ch>=5,hint:'policijska uniforma — poglavlje 5'},8:{need:()=>(GTA.done.pozar||0)>0||(STORY&&STORY.ch>=4),hint:'vatrogasna oprema — ugasi požar'},9:{need:()=>STORY&&STORY.ch>=3,hint:'hitna — poglavlje 3'}};
function openWardrobe(){ if(!HOME.showcase){ const w=(INSIDE&&INSIDE.id==='kuca'&&HOME.wardPos)?HOME.wardPos:homeLocal(-1.55,-2.6); if(w) TPS.face=faceYaw(PLAYER.pos.x-w[0],PLAYER.pos.z-w[1]); } HOME.showcase=true; HOME.wardSkin=OW.skin|0; if(typeof COMBAT!=='undefined'&&COMBAT.armed) holster();
  const items=SKINS.map((s,i)=>{ const L=OUTFIT_LOCK[i]; const ok=!L||L.need(); return {label:s.n.charAt(0).toUpperCase()+s.n.slice(1),sub:ok?(i===(OW.skin|0)?'na tebi':''):'🔒 '+L.hint,right:i===(OW.skin|0)?'✓':'',sel:i===(OW.skin|0),disabled:!ok,fn:()=>{ OW.skin=i; OW.skinSet=true; try{ owSave(); }catch(e){} openWardrobe(); }}; });
  gMenu('Ormar','Odaberi što ćeš obući — vidiš se odmah. Uniforme otključavaš kroz priču.',items,{side:true}); }
/* ---- bed / shower / TV ---- */
function fadeTo(fn,txt){ let f=document.getElementById('fadeov'); if(!f){ f=document.createElement('div'); f.id='fadeov'; f.style.cssText='position:fixed;inset:0;background:#000;opacity:0;transition:opacity .6s;z-index:60;pointer-events:none;display:flex;align-items:center;justify-content:center;color:#f5f1e8;font:400 44px "Instrument Serif",Georgia,serif'; document.body.appendChild(f); }
  f.textContent=txt||''; f.style.opacity='1'; setTimeout(()=>{ try{ fn(); }catch(e){ console.warn(e); } setTimeout(()=>{ f.style.opacity='0'; },700); },700); }
function fadeBlack(on){ fadeTo(()=>{},''); const f=document.getElementById('fadeov'); if(f) f.style.opacity=on?'1':'0'; }
function sleepMenu(){ const h=GAME.hour; gMenu('Krevet','Sad je '+String(Math.floor(h)).padStart(2,'0')+':'+String(Math.floor((h%1)*60)).padStart(2,'0')+'. Spavanjem se igra sprema, a zdravlje se puni.',[
    {label:'Spavaj do jutra',sub:'probudi se u 7:00',fn:()=>doSleep(7)},{label:'Odmori se do popodneva',sub:'15:00',fn:()=>doSleep(15)},{label:'Spavaj do večeri',sub:'20:30 — brtija je puna',fn:()=>doSleep(20.5)}]); }
function doSleep(to){ gMenuClose(); fadeTo(()=>{ GAME.hour=to; setTimeOfDay(GAME.renderer,GAME.scene,to); try{ nightLights(); }catch(e){} COMBAT.hp=100; COMBAT.bac=0; updateCombatHUD(); if(GTA.wanted){ GTA.wanted=0; COP.state='RETURN'; } try{ owSave(); }catch(e){} UI.toast('😴 Naspavao si se — igra je spremljena'); },'Zzz…'); }
function shower(){ fadeTo(()=>{ COMBAT.bac=0; COMBAT.hp=Math.min(100,COMBAT.hp+25); updateCombatHUD(); UI.toast('🚿 Osvježen i trijezan'); },'🚿'); }
function watchTV(){ const N=tvNews(); gMenu('Zagorje TV','Vijesti iz Tuhlja i okolice',N.map(n=>({label:n[0],sub:n[1],fn:()=>{}})).concat([{label:'Ugasi televizor',fn:gMenuClose}])); }
function tvNews(){ const L=[]; const ch=(typeof STORY!=='undefined')?STORY.ch:0;
  if(GTA.wanted) L.push(['🚓 Policija traga za osobom u Tuhlju','Svjedoci opisuju muškarca koji je pobjegao prema '+(PLAYER.pos.z<-40?'Lipnici':'centru sela')+'.']);
  const S=[['📰 Povratak iz Njemačke','Mladić se nakon deset godina vratio u obiteljsku kuću nasuprot crkve.'],['🍷 Kenka opet duguje','U brtiji šapuću da je Kenka posudio novac od pogrešnih ljudi.'],['🐺 Crni Vukovi u selu','Banda crnih automobila viđena kod Strahinjčice. Mještani se žale.'],['🔥 Požar kod vatrogasnog doma','DVD Tuhelj zahvaljuje hrabrom mještaninu koji je pomogao.'],['🚜 Ukraden traktor','Joži st. nestao je traktor iz štaglja — sumnja se na Vukove.'],['🏛️ Načelnik pod pritiskom','Tko to stoji iza Crnih Vukova? Općina šuti.'],['🎉 Tuhelj slavi','Nakon pada Crnih Vukova, u brtiji se slavi do jutra.']];
  for(let i=0;i<=Math.min(ch,S.length-1);i++) L.push(S[i]); L.reverse(); L.push(['☀️ Prognoza','Sunčano, uz poneki pljusak popodne. Toplice Tuhelj rade do 21 h.']); return L.slice(0,5); }
/* ---- furniture you can buy ---- */
const DECOR=[{k:'tepih',n:'Tepih s uzorkom',p:40},{k:'biljka',n:'Velika biljka (fikus)',p:35},{k:'fotelja',n:'Kožna fotelja',p:120},{k:'zastava',n:'Hrvatska zastava',p:25},{k:'pc',n:'Gaming kompjuter s RGB-om',p:450},{k:'akvarij',n:'Akvarij s ribicama',p:180},{k:'plakat',n:'Uokvirena slika Tuhlja',p:60},{k:'trofej',n:'Vitrina s peharima (misije)',p:90}];
function decorMenu(){ gMenu('Uredi kuću','Kupi namještaj — ostaje u tvojoj kući i nakon što zatvoriš igru.',DECOR.map(D=>{ const has=HOME.decor.has(D.k); return {label:D.n,right:has?'✓ imaš':D.p+' €',disabled:has,fn:()=>{ if(GTA.money<D.p){ UI.toast('Nemaš dovoljno novca'); return; } money(-D.p,'kupio si: '+D.n); HOME.decor.add(D.k); try{ localStorage.setItem('tuhelj_decor',JSON.stringify([...HOME.decor])); }catch(e){} buildDecor(); decorMenu(); }}; })); }
// furniture lives in the family house (room set by buildFamilyHome): slot = [x, z, height, rotation] in room coordinates
function decorAt(k){ const R=HOME.room, S=HOME.slots[k]; const g=new THREE.Group(); g.position.set(R.x+S[0],R.y+S[2],R.z+S[1]); g.rotation.y=S[3]; GAME.scene.add(g); return g; }
function buildDecor(){ if(!HOME.room) return; const M=(c,r=0.7,m=0,e)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,emissive:e||0x000000}); const box=(g,w,h,d,mat,x,y,z)=>{ const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat); b.position.set(x,y,z); b.castShadow=true; b.receiveShadow=true; g.add(b); return b; };
  for(const k of HOME.decor){ if(HOME.built[k]) continue; let g=null;
    if(k==='tepih'){ g=decorAt('tepih'); const c=cvs(256,256), x=c.getContext('2d'); x.fillStyle='#7a2a2a'; x.fillRect(0,0,256,256); x.strokeStyle='#e8c98a'; x.lineWidth=10; x.strokeRect(14,14,228,228); x.lineWidth=4; for(let i=0;i<5;i++){ x.beginPath(); x.arc(128,128,22+i*20,0,TAU); x.stroke(); } const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; const m=new THREE.Mesh(new THREE.PlaneGeometry(1.8,1.4),new THREE.MeshStandardMaterial({map:t,roughness:1})); m.rotation.x=-Math.PI/2; m.receiveShadow=true; g.add(m); }
    if(k==='biljka'){ g=decorAt('biljka'); const pot=new THREE.Mesh(new THREE.CylinderGeometry(0.2,0.15,0.4,14),M(0xb8653d)); pot.position.y=0.2; g.add(pot); for(let i=0;i<16;i++){ const l=new THREE.Mesh(new THREE.SphereGeometry(0.18,8,6),M(0x2f6a2a,0.8)); const a=i*2.4; l.position.set(Math.cos(a)*0.22*(i%3)*0.6,0.6+i*0.06,Math.sin(a)*0.22*(i%3)*0.6); l.scale.set(1,0.6,1); l.castShadow=true; g.add(l); } }
    if(k==='fotelja'){ g=decorAt('fotelja'); const L=M(0x5a3420,0.45); box(g,0.8,0.4,0.75,L,0,0.25,0); box(g,0.8,0.55,0.15,L,0,0.65,0.33); box(g,0.14,0.25,0.75,L,-0.36,0.55,0); box(g,0.14,0.25,0.75,L,0.36,0.55,0); }
    if(k==='zastava'){ g=decorAt('zastava'); const c=cvs(300,150), x=c.getContext('2d'); [['#ff0000',0],['#ffffff',50],['#171796',100]].forEach(([col,y])=>{ x.fillStyle=col; x.fillRect(0,y,300,50); }); x.fillStyle='#fff'; x.fillRect(125,30,50,60); for(let i=0;i<5;i++) for(let j=0;j<6;j++){ x.fillStyle=(i+j)%2?'#ff0000':'#ffffff'; x.fillRect(125+i*10,30+j*10,10,10); } const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; const m=new THREE.Mesh(new THREE.PlaneGeometry(1.0,0.5),new THREE.MeshStandardMaterial({map:t,roughness:0.9,side:THREE.DoubleSide})); m.rotation.y=Math.PI; g.add(m); }
    if(k==='pc'){ g=decorAt('pc'); box(g,1.1,0.05,0.55,M(0x1c1c1e,0.4),0,0.74,0); for(const x of [-0.5,0.5]) box(g,0.05,0.74,0.5,M(0x111111,0.4,0.6),x,0.37,0); box(g,0.55,0.33,0.03,M(0x050505,0.2,0.3,0x0a2a4a),0,1.0,-0.18); box(g,0.2,0.45,0.42,M(0x101010,0.3,0.5,0x401060),0.42,0.99,0.0); box(g,0.42,0.02,0.14,M(0x222222,0.5,0,0x2060ff),-0.05,0.77,0.08); const ch=M(0x1a1a1a,0.5); box(g,0.5,0.08,0.5,ch,0,0.48,0.6); box(g,0.5,0.6,0.08,ch,0,0.85,0.83); }
    if(k==='akvarij'){ g=decorAt('akvarij'); box(g,0.9,0.7,0.4,M(0x2a2a2a,0.6),0,0.35,0); const w=new THREE.Mesh(new THREE.BoxGeometry(0.88,0.45,0.38),new THREE.MeshStandardMaterial({color:0x5fb8d8,transparent:true,opacity:0.55,roughness:0.05,emissive:0x0a3040})); w.position.y=0.95; g.add(w); g.userData.fish=[]; for(let i=0;i<5;i++){ const f=new THREE.Mesh(new THREE.ConeGeometry(0.025,0.08,6),M(i%2?0xff8a20:0xffd040,0.4,0,0x402000)); f.rotation.z=Math.PI/2; g.add(f); g.userData.fish.push({m:f,ph:i*1.3}); } HOME.aquarium=g; }
    if(k==='plakat'){ g=decorAt('plakat'); const c=cvs(400,280), x=c.getContext('2d'); const gr=x.createLinearGradient(0,0,0,280); gr.addColorStop(0,'#8fb8de'); gr.addColorStop(0.55,'#e6d8b8'); gr.addColorStop(1,'#5a8a3a'); x.fillStyle=gr; x.fillRect(0,0,400,280); x.fillStyle='#f4f2ea'; x.fillRect(180,90,40,110); x.fillStyle='#2a2a36'; x.beginPath(); x.ellipse(200,85,22,26,0,0,TAU); x.fill(); x.fillStyle='#b8452a'; x.beginPath(); x.moveTo(150,200); x.lineTo(250,200); x.lineTo(200,160); x.fill(); x.fillStyle='#3a6a2a'; for(let i=0;i<14;i++){ x.beginPath(); x.arc(i*32,215+Math.sin(i)*6,26,0,TAU); x.fill(); } x.fillStyle='#fff'; x.font='600 34px Georgia'; x.fillText('Tuhelj',16,44); const t=new THREE.CanvasTexture(c); t.colorSpace=THREE.SRGBColorSpace; box(g,0.92,0.68,0.03,M(0x3a2414,0.6),0,0,0); const m=new THREE.Mesh(new THREE.PlaneGeometry(0.82,0.58),new THREE.MeshStandardMaterial({map:t,roughness:0.6})); m.position.z=0.02; g.add(m); HOME.photo=m; }
    if(k==='trofej'){ g=decorAt('trofej'); box(g,0.3,1.6,0.9,M(0x3a2a1a,0.5),0,0.8,0); const gold=M(0xd4a63a,0.3,0.9); const n=Math.min(8,Object.values(GTA.done).reduce((a,b)=>a+b,0)+((typeof STORY!=='undefined')?STORY.ch:0)); for(let i=0;i<n;i++){ const c=new THREE.Mesh(new THREE.CylinderGeometry(0.06,0.03,0.14,10),gold); c.position.set(0,0.35+Math.floor(i/3)*0.45,-0.28+(i%3)*0.28); g.add(c); } }
    HOME.built[k]=g; } }
/* ---- per frame ---- */
function homeTick(dt){ if(typeof homeIntInit==='function') homeIntInit(); if(HOME.photo&&!HOME.photoSet&&typeof homePhoto==='function') homePhoto();
  if(HOME.aquarium){ for(const F of HOME.aquarium.userData.fish){ F.ph+=dt*0.6; F.m.position.set(Math.sin(F.ph)*0.35,0.9+Math.sin(F.ph*1.7)*0.12,Math.cos(F.ph*1.3)*0.12); F.m.rotation.y=Math.cos(F.ph)>0?0:Math.PI; } } }
