/* ===================== start screen: cinematic fly-through, photos, tips, chapters, new game ===================== */
const LOOK={shot:-1,shotT:0,tipI:0,tipT:0,photoI:0,photoT:0,photos:[]};
const TIPS=[['Policija','Izgubi ih iz vida pa se sakrij — zvjezdice padaju dok te traže. Plavo-crveni krug na karti je gdje te traže.'],['Oružje','Kotačić miša mijenja oružje. Nova oružja dobivaš kroz priču — sačmaricu, snajper i bazuku.'],['Kuća','U stanu Kod Ruže možeš se presvući u ormaru, odspavati (sprema igru) i kupiti namještaj.'],['Brtija','U Kafiću Putniku naruči gemišt kod Valentine ili sjedni za poker. Ne vozi pijan!'],['Hitna','Kad netko padne, dolaze bolničari. Pusti ih da rade — oživjet će ga.'],['Kamera','Tipka V mijenja treće i prvo lice. Desni klik nišani preko ramena.'],['Bazuka','Raketa leti brzo i ostavlja dim — auti koje pogodiš gore pa eksplodiraju.'],['Prijatelji','Upiši ime i pošalji poveznicu prijateljima — vidite se u istom selu.']];
function startShots(){ const L=LANDMARKS, c=CENTER; const ch=L.church?[L.church.x,L.church.z]:[-326,-5], cf=CAFE_POS(), fi=L.fire?[L.fire.x,L.fire.z]:[-131,-19];
  return [{c:ch,r:62,h:26,la:12,sp:0.07,a0:0.3},{c:cf,r:26,h:5,la:2,sp:0.05,a0:2.2},{c,r:190,h:95,la:0,sp:0.035,a0:4.0},{c:fi,r:34,h:9,la:3,sp:-0.06,a0:1.0},{c:[START.x,START.z],r:70,h:16,la:6,sp:0.05,a0:5.2}]; }
function startCam(camera,dt){ if(!LOOK.shots) LOOK.shots=startShots(); LOOK.shotT-=dt; if(LOOK.shot<0||LOOK.shotT<=0){ LOOK.shot=(LOOK.shot+1)%LOOK.shots.length; LOOK.shotT=8; LOOK.t0=GAME.time; const f=document.getElementById('shotfade'); if(f){ f.classList.add('on'); setTimeout(()=>f.classList.remove('on'),420); } }
  const S=LOOK.shots[LOOK.shot]; const a=S.a0+(GAME.time-LOOK.t0)*S.sp; const x=S.c[0]+Math.cos(a)*S.r, z=S.c[1]+Math.sin(a)*S.r; const gy=Math.max(getHeight(x,z),getHeight(S.c[0],S.c[1]));
  camera.position.set(x,gy+S.h,z); camera.lookAt(S.c[0],getHeight(S.c[0],S.c[1])+S.la,S.c[1]); }
function lookTick(dt){ if(GAME.started) return;
  LOOK.tipT-=dt; if(LOOK.tipT<=0){ LOOK.tipT=6; const el=document.getElementById('tip'); if(el){ const T=TIPS[LOOK.tipI++%TIPS.length]; el.style.opacity='0'; setTimeout(()=>{ el.innerHTML=''; const b=document.createElement('b'); b.textContent='Savjet · '+T[0]; el.append(b,document.createTextNode(T[1])); el.style.opacity='1'; },400); } }
  if(LOOK.photos.length>1){ LOOK.photoT-=dt; if(LOOK.photoT<=0){ LOOK.photoT=7; const im=LOOK.photos; im.forEach((m,i)=>m.classList.toggle('on',i===LOOK.photoI%im.length)); LOOK.photoI++; } } }
function lookInit(){ // photos → slideshow; chapter progress; buttons
  const P=Array.isArray(window.TUHELJ_PHOTOS)?window.TUHELJ_PHOTOS:[]; const sl=document.getElementById('slides');
  if(P.length&&sl){ for(const u of P){ const im=new Image(); im.src=u; im.alt=''; im.decoding='async'; sl.appendChild(im); LOOK.photos.push(im); } LOOK.photos[0].classList.add('on'); sl.classList.add('on'); }
  const ch=document.getElementById('chap'); if(ch){ const n=(typeof STORY!=='undefined')?STORY.ch:0; for(let i=0;i<7;i++){ const s=document.createElement('i'); if(i<n) s.className='d'; ch.appendChild(s); } const b=document.createElement('b'); b.textContent=n>=7?'Priča završena':n?('Poglavlje '+(n+1)+' / 7'):'Nova priča'; ch.appendChild(b); }
  const ng=document.getElementById('newgame'); if(ng){ const any=(typeof STORY!=='undefined'&&STORY.ch>0)||GTA.home; ng.style.display=any?'':'none'; ng.addEventListener('click',()=>{ if(!confirm('Započeti priču ispočetka? Novac, stan, oružje i namještaj se brišu.')) return; try{ for(const k of ['tuhelj_story','tuhelj_money','tuhelj_home','tuhelj_done','tuhelj_arms','tuhelj_decor','tuhelj_save']) localStorage.removeItem(k); }catch(e){} location.reload(); }); } }
function goLabel(){ const n=(typeof STORY!=='undefined')?STORY.ch:0; return n>=7?'Igraj slobodno':n?'Nastavi priču':'Započni priču'; }
/* your own photo framed on the wall at home (first photo from photos/) */
function homePhoto(){ const P=window.TUHELJ_PHOTOS; if(!P||!P.length||!HOME.photo||HOME.photoSet) return; HOME.photoSet=true; new THREE.TextureLoader().load(P[0],t=>{ t.colorSpace=THREE.SRGBColorSpace; HOME.photo.material.map=t; HOME.photo.material.needsUpdate=true; }); }
