/* ===================== money has a purpose: cars, a garage, property and tuning =====================
   Phone → 🚗 Autokuća: buy a car in the colour you like; it is delivered in front of your house and stays yours
   (saved). Without a garage there is room for 2 of your own cars, with the garage for 5.
   Phone → 🏠 Nekretnine: the garage, a holiday house at Pristava 82 rented to guests of the spa, a share in the
   Strahinjčica shop and the brtija itself. Property pays every morning at 8.
   Garage at home: drive any car up to your house and press E (or the button) for paint, rims and engine tuning.
   Tuning of your own cars is saved. */
const OWN=(()=>{ const d={cars:[],props:{},day:-1}; try{ const s=JSON.parse(localStorage.getItem('tuhelj_own')||'null'); if(s&&typeof s==='object') return Object.assign(d,s); }catch(e){} return d; })();
function ownSave(){ try{ localStorage.setItem('tuhelj_own',JSON.stringify(OWN)); }catch(e){} }
const DEALER=[{t:'hatch',n:'Gradski hatchback',p:4500},{t:'sedan',n:'Limuzina',p:7000},{t:'taxi',n:'Karavan (bivši taksi)',p:5500},{t:'suv',n:'SUV',p:9500},{t:'troc',n:'Crossover',p:12000},{t:'sport',n:'Sportski kupe',p:19000},{t:'sport2',n:'Super sport',p:26000}];
const CAR_PAINTS=[['Bijela','#f2f2ef'],['Crna','#141518'],['Srebrna','#a7abb0'],['Crvena','#b3121c'],['Plava','#1f4fa8'],['Zelena','#2f6b3a'],['Žuta','#e8b81a'],['Narančasta','#e0661a'],['Ljubičasta','#5b2a7a']];
const ESTATES=[{id:'garaza',n:'Garaža kraj kuće',p:1500,inc:0,d:'Mjesto za 5 tvojih auta (bez nje 2)'},{id:'vikendica',n:'Vikendica Pristava 82',p:9000,inc:70,d:'Iznajmljuješ je gostima Terma Tuhelj'},{id:'trgovina',n:'Udio u trgovini Strahinjčica',p:14000,inc:110,d:'Dio zarade od trgovine'},{id:'brtija',n:'Kafić Putniku (brtija)',p:25000,inc:240,d:'Sva zarada brtije je tvoja. Lidija ostaje šefica šanka.'}];
function carSlots(){ return OWN.props.garaza?5:2; }
function ownHomeSpots(){ const F=PHOTO.F; if(!F) return [[START.x+3,START.z+6,0]]; const hw=5; return [4.2,8.8,-10.2,13.4,-14.8].map(x=>{ const q=F(x,0,hw+3.15), d=F(x+1,0,hw+3.15); return [q[0],q[2],faceYaw(d[0]-q[0],d[2]-q[2])]; }); }
function ownSpawn(c,i){ const s=ownHomeSpots()[i%5]; const v=makeCarGroup(c.t,c.col); v.label=c.n; v.owned=c; placeVehicle(GAME.scene,v,s[0],s[1],s[2]); ownApplyTune(v); return v; }
function ownApplyTune(v){ const c=v.owned||v.tune; const t=c&&c.tune||v.tuneLive; if(!t) return; if(t.col) carRepaint(v,t.col); if(t.rim) carRims(v,t.rim); if(t.eng){ const base={maxV:v.truck?24:34,rev:-7,acc:v.truck?5.2:7.5,brake:16,maxSteer:v.truck?0.5:0.62,sv:9}; v.phys=Object.assign({},v.phys0||base); v.phys0=v.phys0||Object.assign({},v.phys||base); v.phys.maxV=v.phys0.maxV*(1+0.09*t.eng); v.phys.acc=v.phys0.acc*(1+0.2*t.eng); } }
function carRepaint(v,col){ if(v.paint) v.paint.color.set(col); v.group.traverse(o=>{ const m=o.material; if(!o.isMesh||!m||m===v.paint) return; if(m.metalness===0.55&&m.roughness===0.3&&m.envMapIntensity===1.2){ m.color.set(col).multiplyScalar(0.72); } }); }
function carRims(v,col){ for(const w of (v.wheels||[])){ w.spin.traverse(o=>{ if(!o.isMesh||!o.material) return; const m=o.material; const l=m.color?(m.color.r+m.color.g+m.color.b)/3:0; if(l<0.12&&!m.userData.rim) return; if(!m.userData.rim){ o.material=m.clone(); o.material.userData.rim=true; } o.material.color.set(col); o.material.metalness=0.8; o.material.roughness=0.25; }); } }
let OWN_SPAWNED=false; function ownSpawnAll(){ if(OWN_SPAWNED||!GAME.scene) return; OWN_SPAWNED=true; OWN.cars.forEach((c,i)=>{ try{ ownSpawn(c,i); }catch(e){ console.warn('auto',e); } }); }
/* ---- modal menu (same look as the shop) ---- */
function ownMenu(title,sub,rows){ let el=document.getElementById('ownmenu'); if(!el){ el=document.createElement('div'); el.id='ownmenu'; el.innerHTML='<div class="dm"><h3></h3><p></p><div class="ol"></div><button class="btn">Zatvori</button></div>'; document.body.appendChild(el); el.querySelector('.btn').addEventListener('click',()=>ownClose());
    const st=document.createElement('style'); st.textContent='#ownmenu{position:fixed;inset:0;z-index:70;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.55)} #ownmenu.on{display:flex} #ownmenu .dm{width:min(520px,92vw);max-height:86vh;overflow:auto;background:#161819;color:#fff;border-radius:16px;padding:18px 20px;font-family:Manrope,sans-serif} #ownmenu h3{margin:0 0 4px;font:400 28px Anton,Impact,sans-serif;letter-spacing:.03em} #ownmenu p{margin:0 0 12px;opacity:.7;font-size:13px} #ownmenu .ol{display:flex;flex-direction:column;gap:6px} #ownmenu .ol button{display:flex;justify-content:space-between;gap:12px;text-align:left;background:rgba(255,255,255,.07);border:0;color:#fff;border-radius:10px;padding:11px 14px;font:700 14px Manrope,sans-serif;cursor:pointer} #ownmenu .ol button.dim{opacity:.45} #ownmenu .ol button b{color:#ffd24a;white-space:nowrap} #ownmenu .ol .sw{width:22px;height:22px;border-radius:50%;border:2px solid #fff;flex:none} #ownmenu .ol h5{margin:10px 0 2px;font:800 12px Manrope;letter-spacing:.16em;color:#ffd24a} #ownmenu .btn{margin-top:14px;width:100%;padding:12px;border-radius:10px;border:0;background:#f4f1ea;color:#111;font:800 14px Manrope,sans-serif}'; document.head.appendChild(st); }
  el.querySelector('h3').textContent=title; el.querySelector('p').textContent=sub||''; const L=el.querySelector('.ol'); L.replaceChildren();
  for(const r of rows){ if(r.head){ const h=document.createElement('h5'); h.textContent=r.head; L.appendChild(h); continue; } const b=document.createElement('button'); if(r.dim) b.className='dim'; const s=document.createElement('span'); s.style.display='flex'; s.style.alignItems='center'; s.style.gap='10px'; if(r.sw){ const w=document.createElement('i'); w.className='sw'; w.style.background=r.sw; s.appendChild(w); } s.appendChild(document.createTextNode(r.t)); const p=document.createElement('b'); p.textContent=r.p||''; b.append(s,p); b.addEventListener('click',()=>{ try{ uiSnd('pick'); }catch(e){} r.fn&&r.fn(); }); L.appendChild(b); }
  el.classList.add('on'); COMBAT.menuOpen=true; PLAYER.enabled=false; if(document.pointerLockElement) document.exitPointerLock(); }
function ownClose(){ const el=document.getElementById('ownmenu'); if(el) el.classList.remove('on'); COMBAT.menuOpen=false; PLAYER.enabled=true; if(!GAME.touch&&!GAME.dragLook){ try{ GAME.renderer.domElement.requestPointerLock(); }catch(e){} } }
function pay(p,why){ if(GTA.money<p){ UI.toast('Nemaš dovoljno novca ('+p.toLocaleString('hr-HR')+' €)'); return false; } money(-p,why); return true; }
/* ---- car dealer ---- */
function dealerMenu(pick){ if(!pick){ ownMenu('AUTOKUĆA ZAGORJE','Dostava pred tvoju kuću · tvojih auta: '+OWN.cars.length+' / '+carSlots(),DEALER.map(D=>({t:D.n,p:D.p.toLocaleString('hr-HR')+' €',fn:()=>dealerMenu(D)}))); return; }
  ownMenu(pick.n.toUpperCase(),'Odaberi boju',CAR_PAINTS.map(([n,c])=>({t:n,sw:c,p:pick.p.toLocaleString('hr-HR')+' €',fn:()=>{ if(OWN.cars.length>=carSlots()){ UI.toast(OWN.props.garaza?'Garaža je puna (5 auta)':'Nema mjesta — kupi garažu u Nekretninama'); return; } if(!pay(pick.p,'kupio auto')) return;
    const car={t:pick.t,n:pick.n,col:c,tune:{}}; OWN.cars.push(car); ownSave(); const v=ownSpawn(car,OWN.cars.length-1); ownClose(); if(!GTA.mission){ setWay([v.st.x,v.st.z]); OWN_WAY.v=v; } banner(pick.n.toUpperCase(),'NOVI AUTO · ČEKA TE PRED KUĆOM','#6fe08a'); }})).concat([{t:'◀ Natrag',fn:()=>dealerMenu()}])); }
/* ---- property ---- */
function propMenu(){ ownMenu('NEKRETNINE','Zarada stiže svako jutro u 8 h',ESTATES.map(P=>({t:(OWN.props[P.id]?'✅ ':'')+P.n+' — '+P.d+(P.inc?' · +'+P.inc+' €/dan':''),p:OWN.props[P.id]?'tvoje':P.p.toLocaleString('hr-HR')+' €',dim:!!OWN.props[P.id],fn:()=>{ if(OWN.props[P.id]) return; if(!pay(P.p,'kupio '+P.n)) return; OWN.props[P.id]=1; ownSave(); banner(P.n.toUpperCase(),'TVOJE JE','#6fe08a'); propMenu(); }}))); }
const OWN_WAY={v:null};
function propTick(){ if(!GAME.started) return; if(OWN_WAY.v&&(PLAYER.driving===OWN_WAY.v||GTA.mission)){ if(!GTA.mission) setWay(null); OWN_WAY.v=null; } const h=GAME.hour; if(h>=8&&h<8.2&&OWN.day!==GTA.dayN){ OWN.day=GTA.dayN; let s=0; for(const P of ESTATES) if(OWN.props[P.id]) s+=P.inc; if(s>0){ money(s,'zarada od nekretnina'); try{ sendMsg('Lidija','Dobro jutro, šefe! Jučerašnja zarada: '+s+' €'); }catch(e){} } ownSave(); }
  if(h<1&&!GTA.dayFlip){ GTA.dayN=(GTA.dayN||0)+1; GTA.dayFlip=true; } if(h>2) GTA.dayFlip=false; }
/* ---- garage at home: paint, rims, engine ---- */
function garageNear(){ const v=PLAYER.driving; if(!v||v.bike||v.heli||!PHOTO.F) return false; const q=PHOTO.F(0,0,8); return Math.hypot(v.st.x-q[0],v.st.z-q[2])<16&&Math.abs(v.st.v)<1.5; }
function tuneOf(v){ if(v.owned){ v.owned.tune=v.owned.tune||{}; return v.owned.tune; } return v.tuneLive=(v.tuneLive||{}); }
function garageMenu(){ const v=PLAYER.driving; if(!v) return; const T=tuneOf(v); const lvl=T.eng|0;
  const rows=[{head:'BOJA · 250 €'}].concat(CAR_PAINTS.map(([n,c])=>({t:n,sw:c,p:'250 €',fn:()=>{ if(!pay(250,'lakiranje')) return; T.col=c; carRepaint(v,c); if(v.owned){ v.owned.col=c; ownSave(); } garageMenu(); }})));
  rows.push({head:'FELGE · 400 €'}); for(const [n,c] of [['Krom','#d8dce0'],['Crne','#1a1b1d'],['Zlatne','#c9a227'],['Crvene','#a3141c']]) rows.push({t:n,sw:c,p:'400 €',fn:()=>{ if(!pay(400,'felge')) return; T.rim=c; carRims(v,c); if(v.owned) ownSave(); garageMenu(); }});
  rows.push({head:'MOTOR · stupanj '+lvl+' / 3'}); if(lvl<3){ const pr=[800,1600,3000][lvl]; rows.push({t:'Motor stupanj '+(lvl+1)+' (+'+[9,18,27][lvl]+'% brzina, +'+[20,40,60][lvl]+'% ubrzanje)',p:pr+' €',fn:()=>{ if(!pay(pr,'tuning motora')) return; T.eng=lvl+1; ownApplyTune(v); if(v.owned) ownSave(); garageMenu(); }}); } else rows.push({t:'Motor je na maksimumu',dim:true});
  rows.push({head:'POPRAVAK'},{t:'Popravi auto',p:'60 €',fn:()=>{ if(!pay(60,'popravak')) return; v.hp=100; v.wreck=false; try{ if(typeof repairVehicle==='function') repairVehicle(v); }catch(e){} UI.toast('🔧 Auto je popravljen'); }});
  ownMenu('GARAŽA','Tvoj auto'+(v.owned?'':' (tuning tuđeg auta se ne sprema — kupi svoj u Autokući)'),rows); }
/* ---- wiring ---- */
{ const _rp=renderPhone; renderPhone=function(){ _rp(); const el=document.getElementById('phonebody'); if(!el||!OW.phone) return; if(OW.app!=='home') return;
    const add=(ic,txt,fn)=>{ const b=document.createElement('button'); b.className='papp'; const i=document.createElement('span'); i.className='pi'; i.textContent=ic; const t=document.createElement('span'); t.textContent=txt; b.append(i,t); b.addEventListener('click',()=>{ togglePhone(false); setTimeout(fn,60); }); el.insertBefore(b,el.children[5]||null); };
    add('🚗','Autokuća',()=>dealerMenu()); add('🏠','Nekretnine',()=>propMenu()); }; }
{ const _ip=intPrompt; intPrompt=function(){ const t=_ip(); if(t) return t; return garageNear()?'🔧 Garaža — tuning':''; }; }
{ const _gu=gtaUse; gtaUse=function(){ if(garageNear()&&!GTA.dlg){ garageMenu(); return true; } return _gu(); }; }
{ const _sg=startGame; startGame=function(){ _sg(); try{ ownSpawnAll(); }catch(e){ console.warn(e); } }; }
setInterval(()=>{ try{ propTick(); }catch(e){} },1000);
addEventListener('keydown',e=>{ if(e.code==='Escape'){ const el=document.getElementById('ownmenu'); if(el&&el.classList.contains('on')){ e.preventDefault(); ownClose(); } } });
