/* ===================== side jobs that repeat and pay =====================
   Phone → 💼 Poslovi. Start a job and it keeps giving you work until you stop it (phone, or the job card ✕):
   · Taksi — any car: pick up the passenger waving by the road, drive them where they want, faster = bigger tip.
   · Dostava pizze — pizzas from the brtija to three houses per round, against the clock.
   · Hitna pomoć — someone collapsed by the road: get them to the ambulance at the town hall in time.
   · Vatrogasac — fire engine: every fire in the village is yours; put it out and get paid.
   The target is always on the radar and marked with the yellow beam. */
const JOB={k:null,st:'',t:0,tgt:null,pax:null,dest:null,n:0,earn:0,lim:0,batch:0};
const JOB_NAMES={taxi:'🚕 Taksi',pizza:'🍕 Dostava pizze',hitna:'🚑 Hitna pomoć',vatro:'🚒 Vatrogasac'};
const FIRST=['Štef','Barica','Mirko','Dragica','Ivek','Marica','Joža','Ankica','Tomo','Vesna','Pero','Ljubica'];
function jobRoadPt(minD,maxD){ for(let k=0;k<30;k++){ const a=Math.random()*TAU, r=minD+Math.random()*(maxD-minD); const n=nearestRoad(PLAYER.pos.x+Math.cos(a)*r,PLAYER.pos.z+Math.sin(a)*r,60); if(n){ const w=(n.s.w||6)/2+1.6; const side=Math.random()<0.5?1:-1; return [n.s.x-n.s.tz*w*side,n.s.z+n.s.tx*w*side]; } } return [PLAYER.pos.x+40,PLAYER.pos.z]; }
function jobHouse(minD,maxD){ const L=BLD.filter(b=>b.rect&&(b.k==='house'||b.k===undefined)&&!b.custom).filter(b=>{ const d=Math.hypot(b.rect[0]-PLAYER.pos.x,b.rect[1]-PLAYER.pos.z); return d>minD&&d<maxD; }); const b=L[Math.floor(Math.random()*L.length)]; if(!b) return jobRoadPt(minD,maxD); const n=nearestRoad(b.rect[0],b.rect[1],40); return n?[n.s.x+(b.rect[0]-n.s.x)*0.35,n.s.z+(b.rect[1]-n.s.z)*0.35]:[b.rect[0],b.rect[1]]; }
function jobPerson(x,z,lying){ const nm=FIRST[Math.floor(Math.random()*FIRST.length)]; const A=makePerson(nm,['#7a3b2a','#2a4f7a','#5a6b2a','#6b2a5a'][Math.floor(Math.random()*4)]); A.name=nm; A.noCrime=true; A.group.position.set(x,groundAt(x,z),z); GAME.scene.add(A.group); EXTRA_PEOPLE.push(A);
  if(lying){ A.dead=true; A.deadT=1e9; A.hp=0; A.noRevive=true; A.deadPos=A.group.position.clone(); A.deadYaw=Math.random()*TAU; } return A; }
function jobDrop(A){ if(!A) return; GAME.scene.remove(A.group); if(A.real) try{ detachReal(A); }catch(e){} const i=EXTRA_PEOPLE.indexOf(A); if(i>=0) EXTRA_PEOPLE.splice(i,1); }
function jobPay(base,timeLeft){ const tip=Math.max(0,Math.round(timeLeft*0.6)); const s=base+tip; money(s,'posao'); JOB.earn+=s; JOB.n++; UI.toast('💶 +'+s+' €'+(tip?' (napojnica '+tip+' €)':'')); return s; }
function jobCar(){ const v=PLAYER.driving; return v&&!v.bike&&!v.heli?v:null; }
function jobStart(k){ if(GTA.mission){ UI.toast('Prvo završi misiju'); return; } jobStop(true); JOB.k=k; JOB.n=0; JOB.earn=0; JOB.st='new'; JOB.t=0; banner(JOB_NAMES[k].toUpperCase().replace(/^\S+\s/,''),'POSAO · KRENI','#ffd24a'); jobNext(); }
function jobStop(silent){ if(!JOB.k) return; jobDrop(JOB.pax); JOB.pax=null; if(!silent) UI.toast(JOB_NAMES[JOB.k]+' gotov · zarada '+JOB.earn+' € ('+JOB.n+'×)'); JOB.k=null; JOB.st=''; setWay(null); const c=document.getElementById('jobcard'); if(c) c.style.display='none'; }
function jobNext(){ const k=JOB.k; JOB.t=0;
  if(k==='taxi'){ const p=jobRoadPt(90,320); JOB.pax=jobPerson(p[0],p[1]); JOB.tgt=p; JOB.st='pick'; JOB.lim=0; }
  if(k==='pizza'){ JOB.st='load'; JOB.tgt=CAFE_POS(); JOB.batch=0; JOB.lim=0; }
  if(k==='hitna'){ const p=jobRoadPt(120,360); JOB.pax=jobPerson(p[0],p[1],true); JOB.tgt=p; JOB.st='pick'; JOB.lim=Math.hypot(p[0]-PLAYER.pos.x,p[1]-PLAYER.pos.z)/9+40; }
  if(k==='vatro'){ if(!LIFE.fire) startFire(); JOB.st='fire'; JOB.lim=0; } }
function jobAmb(){ const t=LANDMARKS.townhall; return t?s2Road(t.x,t.z,40):[-294,-55]; }
function jobTick(dt){ if(!JOB.k||!GAME.started) return; if(GTA.mission){ jobStop(); return; } JOB.t+=dt; const v=jobCar(); const p=PLAYER.pos; let txt='', lim=JOB.lim?Math.max(0,JOB.lim-JOB.t):0;
  const near=(q,r)=>q&&Math.hypot(q[0]-p.x,q[1]-p.z)<r, slow=()=>v&&Math.abs(v.st.v)<2.5;
  if(JOB.k==='taxi'){ if(JOB.st==='pick'){ txt=v?'Pokupi putnika ('+JOB.pax.name+')':'Uđi u auto'; if(JOB.pax&&!JOB.pax.real&&Math.random()<0.02) bubble(JOB.pax,'Taksi!',1.5); if(v&&near(JOB.tgt,7)&&slow()){ const d=jobHouse(180,600); JOB.dest=d; JOB.tgt=d; JOB.fare=Math.round(18+Math.hypot(d[0]-p.x,d[1]-p.z)*0.08); JOB.st='drive'; JOB.t=0; JOB.lim=Math.hypot(d[0]-p.x,d[1]-p.z)/8+25; JOB.pax.group.visible=false; JOB.pax.hideAll=true; sayDialog([[JOB.pax.name,['Do '+placeName(d[0],d[1])+', molim. Brzo ako može!','Vozite me tam, žurim na posel.','Dobar dan! Odvezite me do one kuće, hvala.'][Math.floor(Math.random()*3)]]]); } }
    else { txt='Odvezi '+JOB.pax.name+' · ⏱ '+Math.ceil(lim)+' s'; if(!v){ txt='Vrati se u auto!'; } if(v&&near(JOB.tgt,9)&&slow()){ const d=JOB.dest; JOB.pax.group.visible=true; JOB.pax.hideAll=false; JOB.pax.group.position.set(p.x+2,groundAt(p.x+2,p.z),p.z); jobPay(JOB.fare||20,lim); const A=JOB.pax; JOB.pax=null; setTimeout(()=>jobDrop(A),4000); setTimeout(()=>{ if(JOB.k==='taxi') jobNext(); },2500); JOB.st='wait'; } } }
  if(JOB.k==='pizza'){ if(JOB.st==='load'){ txt='Pokupi pizze u brtiji'; if(near(JOB.tgt,9)){ JOB.st='go'; JOB.batch=0; UI.toast('🍕 3 pizze u autu'); JOB.tgt=jobHouse(80,420); JOB.t=0; JOB.lim=Math.hypot(JOB.tgt[0]-p.x,JOB.tgt[1]-p.z)/8+30; } }
    else if(JOB.st==='go'){ txt='Dostavi pizzu '+(JOB.batch+1)+'/3 · ⏱ '+Math.ceil(lim)+' s'; if(lim<=0){ UI.toast('🍕 Pizza je hladna — nema napojnice'); } if(near(JOB.tgt,8)&&(!v||slow())){ jobPay(12,lim); JOB.batch++; if(JOB.batch>=3){ JOB.st='load'; JOB.tgt=CAFE_POS(); JOB.lim=0; UI.toast('Vrati se po nove pizze'); } else { JOB.tgt=jobHouse(60,380); JOB.t=0; JOB.lim=Math.hypot(JOB.tgt[0]-p.x,JOB.tgt[1]-p.z)/8+28; } } } }
  if(JOB.k==='hitna'){ if(lim<=0&&JOB.st!=='wait'){ UI.toast('🚑 Prekasno… pacijent nije preživio'); jobDrop(JOB.pax); JOB.pax=null; JOB.st='wait'; setTimeout(()=>{ if(JOB.k==='hitna') jobNext(); },4000); }
    else if(JOB.st==='pick'){ txt='Hitno: pacijent kraj ceste · ⏱ '+Math.ceil(lim)+' s'; if(v&&near(JOB.tgt,7)&&slow()){ JOB.pax.group.visible=false; JOB.pax.hideAll=true; JOB.st='drive'; JOB.tgt=jobAmb(); JOB.lim=JOB.t+Math.hypot(JOB.tgt[0]-p.x,JOB.tgt[1]-p.z)/8+30; UI.toast('🚑 Pacijent je u autu — vozi u ambulantu!'); } }
    else if(JOB.st==='drive'){ txt='Vozi u ambulantu kod općine · ⏱ '+Math.ceil(lim)+' s'; if(near(JOB.tgt,10)&&(!v||slow())){ jobPay(45,lim); jobDrop(JOB.pax); JOB.pax=null; JOB.st='wait'; setTimeout(()=>{ if(JOB.k==='hitna') jobNext(); },3000); } } }
  if(JOB.k==='vatro'){ if(JOB.st==='fire'){ if(!LIFE.fire){ jobPay(120,0); JOB.st='wait'; UI.toast('🚒 Sljedeća dojava za 20 s'); setTimeout(()=>{ if(JOB.k==='vatro'){ startFire(); JOB.st='fire'; } },20000); } else { txt=(v&&v.truck)?'Ugasi požar (G / 💧)':'Sjedni u vatrogasni kamion'; JOB.tgt=(v&&v.truck)?[LIFE.fire.x,LIFE.fire.z]:(()=>{ const t=DRIVE.find(q=>q.truck); return t?[t.st.x,t.st.z]:null; })(); } } else txt='Čekaj dojavu…'; }
  if(JOB.st!=='wait'&&JOB.tgt) setWay(JOB.tgt); else setWay(null);
  let c=document.getElementById('jobcard'); if(!c){ c=document.createElement('div'); c.id='jobcard'; c.innerHTML='<b></b><span></span><i>✕</i>'; document.body.appendChild(c); c.querySelector('i').addEventListener('pointerdown',e=>{ e.preventDefault(); e.stopPropagation(); jobStop(); });
    const st=document.createElement('style'); st.textContent='#jobcard{position:fixed;z-index:29;left:calc(16px + env(safe-area-inset-left,0px));top:calc(120px + env(safe-area-inset-top,0px));display:none;flex-direction:column;gap:2px;background:rgba(10,12,14,.72);border-left:4px solid #ffd24a;padding:8px 34px 8px 12px;border-radius:6px;color:#fff;font:600 13px Manrope,sans-serif;max-width:min(330px,60vw)} #jobcard b{font:800 12px Manrope;letter-spacing:.14em;color:#ffd24a} #jobcard i{position:absolute;right:8px;top:6px;font-style:normal;cursor:pointer;opacity:.75;font-size:16px;pointer-events:auto} body.touch #jobcard{top:calc(160px + env(safe-area-inset-top,0px))}'; document.head.appendChild(st); }
  c.style.display='flex'; c.querySelector('b').textContent=JOB_NAMES[JOB.k]+' · '+JOB.n+'× · '+JOB.earn+' €'; c.querySelector('span').textContent=txt||'…'; }
{ const _rp=renderPhone; renderPhone=function(){ _rp(); const el=document.getElementById('phonebody'); if(!el||!OW.phone) return;
    if(OW.app==='home'){ const b=document.createElement('button'); b.className='papp'; const i=document.createElement('span'); i.className='pi'; i.textContent='💼'; const t=document.createElement('span'); t.textContent='Poslovi'+(JOB.k?' · '+JOB_NAMES[JOB.k].replace(/^\S+\s/,''):''); b.append(i,t); b.addEventListener('click',()=>{ OW.app='jobs'; renderPhone(); }); el.insertBefore(b,el.children[5]||null); return; }
    if(OW.app==='jobs'){ const add=(ic,txt,fn)=>{ const b=document.createElement('button'); b.className='papp'; const i=document.createElement('span'); i.className='pi'; i.textContent=ic; const t=document.createElement('span'); t.textContent=txt; b.append(i,t); b.addEventListener('click',fn); el.append(b); };
      if(JOB.k) add('⏹','Završi posao ('+JOB.earn+' €)',()=>{ jobStop(); renderPhone(); });
      for(const [k,d] of [['taxi','bilo koji auto'],['pizza','iz brtije, 3 kuće po turi'],['hitna','pacijent u ambulantu na vrijeme'],['vatro','vatrogasni kamion']]) add(JOB_NAMES[k].split(' ')[0],JOB_NAMES[k].replace(/^\S+\s/,'')+' — '+d,()=>{ togglePhone(false); jobStart(k); }); } }; }
{ const _ct=combatTick; combatTick=function(dt){ _ct(dt); try{ jobTick(dt); }catch(e){ if(!JOB.err){ JOB.err=1; console.warn('posao',e); } } }; }
